/* Nights V9.2: selectable ETA ownership and deeper partner collaboration. */
let v92Ready=false,v92JoinedWatch=null,v92JoinedNativeWatch=null,v92JoinedPoints=[],v92JoinedLastSent=0,v92SharedPlans=[],v92SharedActive=null,v92EtaSwitching=false,v92SyncState={state:'local',lastSuccess:0,lastError:'',partnerUpdatedAt:0};
const V92_SYNC_COLLECTIONS=['walks','landmarks','visits','photos','plans','collections','voiceNotes','pines','houses'];

async function v92Init(){
  if(v92Ready)return;v92Ready=true;settings.etaSource=['mine','partner','both'].includes(settings.etaSource)?settings.etaSource:'mine';
  v92Styles();v92BuildUI();v92InstallEtaControls();v92InstallSyncReliability();v92InstallSharedTracking();v92InstallSharedPlans();v92InstallMemories();v92InstallAccountTools();
  await v92RefreshPartnerLabels();v92RenderSyncHealth();if(settings.token){v92RegisterDevice().catch(()=>{});v92RefreshSharedPlans().catch(()=>{});v92RefreshApprovals().catch(()=>{})}
  setInterval(()=>{if(settings.token){v92RefreshSharedPlans().catch(()=>{});v92RenderSyncHealth()}},15000);
}

function v92Styles(){const s=document.createElement('style');s.textContent=`
.v92-eta-source{display:flex;align-items:center;gap:7px;padding:7px 9px;border-radius:12px;background:#eef4ff;color:#28456d;font:600 12px Arial}.v92-eta-source select{min-height:32px!important;padding:4px 8px!important;margin:0!important;max-width:150px;background:white!important}.v92-source-note{font:11px Arial;color:#59708f;margin:4px 2px}.v92-sync-badge{display:inline-flex;align-items:center;gap:6px;border-radius:16px;padding:5px 10px;font:700 11px Arial;background:#e9edf2;color:#425267}.v92-sync-badge:before{content:'';width:8px;height:8px;border-radius:50%;background:#8793a2}.v92-sync-badge[data-state=online]{background:#e4f5eb;color:#17623c}.v92-sync-badge[data-state=online]:before{background:#20a45c}.v92-sync-badge[data-state=syncing]{background:#e7f0ff;color:#1959aa}.v92-sync-badge[data-state=syncing]:before{background:#2479df}.v92-sync-badge[data-state=queued],.v92-sync-badge[data-state=error]{background:#fff0dc;color:#874c00}.v92-sync-badge[data-state=queued]:before,.v92-sync-badge[data-state=error]:before{background:#dc7c00}.v92-health-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.v92-health-item{padding:10px;border-radius:10px;background:#f2f4f7}.v92-health-item b{display:block;font-size:18px}.v92-shared-list{display:grid;gap:7px;margin-top:8px}.v92-shared-row{display:flex;align-items:center;gap:8px;padding:9px;border:1px solid #e1e6ec;border-radius:10px}.v92-shared-row>div{flex:1;min-width:0}.v92-shared-row small{display:block;color:#68778a}.v92-joint{display:inline-block;background:#e6f4ff;color:#165c91;border-radius:10px;padding:2px 6px;font-size:10px;margin-left:5px}.v92-approval{padding:9px;border:1px solid #e7c87a;background:#fff8df;border-radius:9px;margin:7px 0}.v92-device{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid #e4e7eb;padding:7px 0}.v92-contributors{background:#edf7f3;border-radius:8px;padding:8px;margin:7px 0;color:#245c48}.v92-pair-card{font-family:monospace;font-size:18px;letter-spacing:2px;background:#111;color:#fff;border-radius:10px;padding:12px;text-align:center;user-select:all}.v92-plan-source{position:absolute;top:72px;left:12px;z-index:648}@media(max-width:600px){.v92-health-grid{grid-template-columns:1fr}.v92-plan-source{right:12px}.v92-eta-source{justify-content:space-between}}
`;document.head.appendChild(s)}

function v92BuildUI(){
  const source=`<label class="v92-eta-source">ETA from <select id="v92EtaSource"><option value="mine">My walks</option><option value="partner">Partner walks</option><option value="both">Both</option></select></label>`;
  $('v91Shell')?.insertAdjacentHTML('beforeend',`<div class="v92-plan-source">${source}</div>`);
  $('settings')?.querySelector('.two-col')?.insertAdjacentHTML('afterend',`<div class="window-card"><h2>ETA data source</h2><p>Choose whose recorded walking and driving network controls routes and arrival times.</p>${source.replace('id="v92EtaSource"','id="v92EtaSourceSettings"')}<div id="v92EtaEvidence" class="v92-source-note"></div></div><div class="window-card"><h2>Partner edit approval</h2><label class="checkline"><input id="v92LandmarkApproval" type="checkbox"> Ask me before my partner moves or changes my landmarks</label><div id="v92Approvals"></div></div>`);
  $('data')?.querySelector('.window-card')?.insertAdjacentHTML('afterend',`<div class="window-card"><h2>Sync Health <span id="v92SyncBadge" class="v92-sync-badge">Local</span></h2><div id="v92Health" class="v92-health-grid"></div><div class="button-row"><button id="v92CheckSync">CHECK NOW</button><button id="v92RetrySync">RETRY QUEUED CHANGES</button></div><details><summary>Connected devices</summary><div id="v92Devices"></div></details></div>`);
  $('signedInPanel')?.insertAdjacentHTML('beforeend',`<div class="window-card"><h2>Quick partner pairing</h2><p>Share this pairing code or copy the pairing link. It contains only your current invite code.</p><div id="v92PairCard" class="v92-pair-card">SIGN IN FIRST</div><div class="button-row"><button id="v92CopyPair">COPY PAIRING LINK</button></div></div>`);
  const sharedDetails=document.createElement('details');sharedDetails.className='v9-card';sharedDetails.innerHTML='<summary>Shared plans</summary><div class="button-row"><button id="v92SharePlan" class="primary">SHARE CURRENT PLAN</button><button id="v92RefreshPlans">REFRESH</button></div><div id="v92SharedPlans" class="v92-shared-list"></div>';$('v91Sheet')?.querySelector('.v91-sheet-body')?.append(sharedDetails);
}

function v92EtaSourceLabel(source=settings.etaSource||'mine'){const partnerName=partner?.displayName||'Partner',mine=account?.displayName||'My';return source==='partner'?`${partnerName}'s walks`:source==='both'?`${mine} + ${partnerName}`:`${mine}'s walks`}
function v92OwnerId(owner){return owner==='partner'?partner?.id:account?.id}
function v92TrackDistance(points){let d=0;for(let i=1;i<(points||[]).length;i++)if(!points[i].segmentBreak)d+=dist(points[i-1],points[i]);return d}
function v92ExpandWalks(rows,datasetOwner){const result=[];for(const walk of rows||[]){const traces=(walk.participantTraces||[]).filter(t=>Array.isArray(t.points)&&t.points.length>1),shared=walk.sharedActivityUid||null;if(traces.length){for(const t of traces)result.push({...walk,uid:`${walk.uid}:${t.userId||t.name}`,title:`${t.name||'Participant'} · ${walk.title||activityLabel(walk)}`,points:t.points,sharedActivityUid:shared||walk.uid,_etaOwnerId:t.userId||'',_etaOwner:t.userId===account?.id?'mine':t.userId===partner?.id?'partner':datasetOwner,distance:v92TrackDistance(t.points),duration:Math.max(0,Number(t.points.at(-1)?.t||0)-Number(t.points[0]?.t||0))});continue}result.push({...walk,_etaOwner:datasetOwner,_etaOwnerId:v92OwnerId(datasetOwner),title:`${datasetOwner==='partner'?(partner?.displayName||'Partner'):(account?.displayName||'Mine')} · ${walk.title||activityLabel(walk)}`})}return result}
function v92FuseTracks(group){const points=group.flatMap(w=>(w.points||[]).map(p=>({...p,_source:w._etaOwnerId||w._etaOwner}))).sort((a,b)=>Number(a.t)-Number(b.t)),buckets=new Map();for(const p of points){const key=Math.round(Number(p.t||0)/5000),rows=buckets.get(key)||[];rows.push(p);buckets.set(key,rows)}const fused=[];for(const rows of buckets.values()){let weight=0,lat=0,lon=0,alt=0,altWeight=0,t=0;for(const p of rows){const w=1/Math.max(9,Number(p.accuracy||35)**2);weight+=w;lat+=Number(p.lat)*w;lon+=Number(p.lon)*w;t+=Number(p.t||0);if(Number.isFinite(Number(p.altitude))){alt+=Number(p.altitude)*w;altWeight+=w}}const best=[...rows].sort((a,b)=>Number(a.accuracy||999)-Number(b.accuracy||999))[0];fused.push({...best,lat:lat/weight,lon:lon/weight,t:t/rows.length,accuracy:Math.max(1,Math.min(...rows.map(p=>Number(p.accuracy||999)))),altitude:altWeight?alt/altWeight:null})}const first=group[0],duration=Math.max(0,Number(fused.at(-1)?.t||0)-Number(fused[0]?.t||0));return{...first,uid:`shared:${first.sharedActivityUid}`,title:`Both · ${String(first.title||'Shared activity').replace(/^.*? · /,'')}`,points:fused,distance:v92TrackDistance(fused),duration,sharedActivityUid:first.sharedActivityUid,_etaOwner:'both',_etaWeight:1}}
async function v92EtaWalkSources(mode='walk',sourceOverride=settings.etaSource||'mine'){const mine=v92ExpandWalks((await all('walks')).filter(w=>(w.activity||'walk')===mode),'mine'),theirs=v92ExpandWalks((partnerSnapshot?.walks||[]).filter(w=>(w.activity||'walk')===mode),'partner'),source=['mine','partner','both'].includes(sourceOverride)?sourceOverride:'mine',allRows=[...mine,...theirs],wanted=source==='mine'?allRows.filter(w=>w._etaOwnerId?(!account?.id||w._etaOwnerId===account.id):w._etaOwner==='mine'):source==='partner'?allRows.filter(w=>w._etaOwnerId?(!partner?.id||w._etaOwnerId===partner.id):w._etaOwner==='partner'):allRows;if(source!=='both')return v92UniqueTracks(wanted);const shared=new Map(),plain=[];for(const w of wanted){if(w.sharedActivityUid)(shared.get(w.sharedActivityUid)||shared.set(w.sharedActivityUid,[]).get(w.sharedActivityUid)).push(w);else plain.push(w)}return[...v92UniqueTracks(plain),...[...shared.values()].map(rows=>rows.length>1?v92FuseTracks(v92UniqueTracks(rows)):rows[0])]}
function v92UniqueTracks(rows){const map=new Map();for(const w of rows){const key=w.sharedActivityUid&&w._etaOwnerId?`${w.sharedActivityUid}:${w._etaOwnerId}`:w.uid;if(!map.has(key)||Number(w.updatedAt)>Number(map.get(key).updatedAt))map.set(key,w)}return[...map.values()]}

function v92InstallEtaControls(){
  for(const id of ['v92EtaSource','v92EtaSourceSettings']){const el=$(id);if(!el)continue;el.value=settings.etaSource;el.onchange=()=>v92SetEtaSource(el.value)}
  const baseAccount=updateAccountUI;updateAccountUI=function(){baseAccount();v92RefreshPartnerLabels();v92RenderPairing()};
  const basePlan=v9RenderRoute;v9RenderRoute=function(route){basePlan(route);if(route&&$('v91RouteInfo'))$('v91RouteInfo').textContent+=` · ${v92EtaSourceLabel()}`;v92RenderEtaEvidence()};
}
async function v92SetEtaSource(source){source=['mine','partner','both'].includes(source)?source:'mine';if(source==='partner'&&!partner)return alert('Link and sync a partner before using partner ETA data.');if(v92EtaSwitching)return;v92EtaSwitching=true;try{if(source!=='mine'&&settings.token&&partner)try{await loadPartnerOnly()}catch{}settings.etaSource=source;saveSettings();for(const id of ['v92EtaSource','v92EtaSourceSettings'])if($(id))$(id).value=source;v9RouteModels={walk:null,drive:null};await rebuildEtaProfile();await v9BuildAllModels(source);v9ScheduleRoute();await renderLists();v92RenderEtaEvidence();const model=v9RouteModels[v9PlanMode||'walk'],usable=model?.trackCount||0;v8Toast(usable?`ETA now uses ${v92EtaSourceLabel(source)} (${usable} usable activities).`:`${v92EtaSourceLabel(source)} selected, but has no usable ${v9PlanMode||'walk'} data yet.`)}catch(e){v8Toast(`Could not rebuild ETA data: ${e.message}`)}finally{v92EtaSwitching=false}}
async function v92RefreshPartnerLabels(){const p=partner?.displayName||'Partner';for(const id of ['v92EtaSource','v92EtaSourceSettings']){const el=$(id);if(el?.options[1])el.options[1].textContent=`${p}'s walks`;if(el?.options[2])el.options[2].textContent=`Mine + ${p}`;if(el)el.value=settings.etaSource||'mine'}v92RenderEtaEvidence();v92RenderPairing()}
function v92RenderEtaEvidence(){const source=settings.etaSource||'mine',model=v9RouteModels[v9PlanMode||'walk'],valid=model?.etaSource===source,q=valid?model.quality:null,el=$('v92EtaEvidence');if(el)el.textContent=valid?(model.trackCount?`${v92EtaSourceLabel(source)} · ${model.trackCount} usable activities · ${q?.accepted||0} accepted GPS segments · ${q?.rejected||0} rejected`:`${v92EtaSourceLabel(source)} · 0 usable activities · this route is a starter estimate, not personalized`):`${v92EtaSourceLabel(source)} selected. The network is rebuilding now.`}

function v92InstallSyncReliability(){
  const basePush=cloudPush;cloudPush=async function(){if(!settings.token)return true;v92SetSyncState('syncing');const snapshot=await localSnapshot(),previous=settings.v92SyncManifest;if(!previous){const ok=await basePush();if(ok){v92RememberManifest(snapshot);await v92SyncSuccess('Full account sync')}else await v92SyncFailure(new Error('The server is unavailable. Changes remain queued.'));return ok}const delta=v92BuildDelta(snapshot,previous);if(!delta.changed){v92SetSyncState('online');return true}try{await authFetch('/api/sync/delta',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(delta)});v92RememberManifest(snapshot);await clearStore('syncQueue');await v92SyncSuccess(`${delta.changed} changes synced`);await loadPartnerOnly();return true}catch(e){if(e.status===404){const ok=await basePush();if(ok){v92RememberManifest(snapshot);await v92SyncSuccess('Compatibility sync')}else await v92SyncFailure(e);return ok}await put('syncQueue',{uid:uid(),kind:'delta',queuedAt:now(),summary:delta.changed});await v92SyncFailure(e);return false}};
  const basePull=cloudPull;cloudPull=async function(){v92SetSyncState('syncing');try{const result=await basePull();await v92SyncSuccess('Downloaded partner changes');return result}catch(e){await v92SyncFailure(e);throw e}};
  const basePartner=loadPartnerOnly;loadPartnerOnly=async function(){try{await basePartner();v92SyncState.partnerUpdatedAt=now();v92SetSyncState('online');if(settings.etaSource!=='mine'&&!v92EtaSwitching){const source=settings.etaSource;v9RouteModels={walk:null,drive:null};await rebuildEtaProfile();await v9BuildAllModels(source);v9ScheduleRoute()}}catch(e){v92SyncState.lastError=e.message;v92SetSyncState(navigator.onLine?'error':'queued');throw e}};
  $('v92CheckSync').onclick=v92CheckSync;$('v92RetrySync').onclick=async()=>{try{await cloudPull();await v92RefreshSharedPlans();await v92RefreshApprovals();v8Toast('Queued changes retried.')}catch(e){alert(`Sync is still unavailable: ${e.message}`)}};
  if($('syncNow'))$('syncNow').onclick=()=>cloudPull().catch(e=>alert(e.message));
  window.addEventListener('online',()=>{v92SetSyncState('syncing');cloudPush().catch(()=>{})});window.addEventListener('offline',()=>v92SetSyncState('queued'));
}
function v92Manifest(snapshot){return Object.fromEntries(V92_SYNC_COLLECTIONS.map(name=>[name,Object.fromEntries((snapshot[name]||[]).filter(x=>x.uid).map(x=>[x.uid,Number(x.updatedAt||x.date||0)]))]))}
function v92RememberManifest(snapshot){settings.v92SyncManifest=v92Manifest(snapshot);settings.v92LastSync=now();saveSettings()}
function v92BuildDelta(snapshot,previous){const changes={},deleted={};let changed=0;for(const name of V92_SYNC_COLLECTIONS){const old=previous[name]||{},rows=(snapshot[name]||[]).filter(x=>x.uid),map=new Map(rows.map(x=>[x.uid,x]));changes[name]=rows.filter(x=>!old[x.uid]||Number(x.updatedAt||x.date||0)>Number(old[x.uid]));deleted[name]=Object.keys(old).filter(key=>!map.has(key));changed+=changes[name].length+deleted[name].length}return{changes,deleted,changed,clientTime:now()}}
async function v92SyncSuccess(message){v92SyncState={...v92SyncState,state:'online',lastSuccess:now(),lastError:''};settings.v92LastSync=now();saveSettings();await put('syncHistory',{uid:uid(),date:now(),ok:true,message});v92RenderSyncHealth()}
async function v92SyncFailure(error){v92SyncState={...v92SyncState,state:navigator.onLine?'error':'queued',lastError:error?.message||String(error)};await put('syncHistory',{uid:uid(),date:now(),ok:false,message:v92SyncState.lastError});v92RenderSyncHealth()}
function v92SetSyncState(state){v92SyncState.state=state;v92RenderSyncHealth()}
async function v92RenderSyncHealth(){const badge=$('v92SyncBadge');if(!badge)return;const queue=await all('syncQueue').catch(()=>[]),history=await all('syncHistory').catch(()=>[]),state=queue.length&&v92SyncState.state!=='syncing'?'queued':v92SyncState.state;badge.dataset.state=state;badge.textContent={online:'Synced',syncing:'Syncing',queued:'Changes queued',error:'Needs attention',local:'Local only'}[state]||state;const last=settings.v92LastSync?new Date(settings.v92LastSync).toLocaleString():'Never',server=settings.apiBase?'Configured':'Missing';$('v92Health').innerHTML=`<div class="v92-health-item"><small>Server</small><b>${server}</b></div><div class="v92-health-item"><small>Partner</small><b>${partner?esc(partner.displayName):'Not linked'}</b></div><div class="v92-health-item"><small>Queued changes</small><b>${queue.length}</b></div><div class="v92-health-item"><small>Last successful sync</small><b style="font-size:12px">${esc(last)}</b></div>${v92SyncState.lastError?`<div class="v92-health-item" style="grid-column:1/-1"><small>Latest problem</small><b style="font-size:12px">${esc(v92SyncState.lastError)}</b></div>`:''}`;if(history.length>100)for(const row of history.sort((a,b)=>Number(a.date)-Number(b.date)).slice(0,-100))remove('syncHistory',row.id).catch(()=>{})}
async function v92CheckSync(){try{let health=null,compatibility=false;try{health=await fetch(apiPath('/api/health'),{cache:'no-store'}).then(apiResponse)}catch(e){if(!settings.token)throw e;compatibility=true}const me=settings.token?await authFetch('/api/me'):null;v92SyncState.lastError='';v92SetSyncState('online');alert(`${compatibility?'The existing Nights server is reachable, but still needs the V9.2 server update.':`Nights server ${health?.version||''} is reachable.`}\n${me?.partner?`Linked to ${me.partner.displayName}.`:'No partner is linked.'}`)}catch(e){v92SyncState.lastError=e.message;v92SetSyncState('error');alert(`Sync check failed: ${e.message}`)}}

function v92InstallSharedTracking(){
  const baseJoin=joinPartnerActivity;joinPartnerActivity=async function(){await baseJoin();if(joinedPartnerActivity)await v92StartJoinedTracking()};$('joinPartnerActivity').onclick=joinPartnerActivity;
  const baseLeave=leavePartnerActivity;leavePartnerActivity=function(){if(joinedPartnerActivity&&settings.token)authFetch('/api/shared-activity/leave',{method:'POST'}).catch(()=>{});v92StopJoinedTracking();baseLeave()};$('leavePartnerActivity').onclick=leavePartnerActivity;
  const basePoll=pollSharedActivity;pollSharedActivity=async function(){const was=joinedPartnerActivity;await basePoll();if(joinedPartnerActivity&&!v92JoinedWatch&&!v92JoinedNativeWatch)await v92StartJoinedTracking();if(was&&!joinedPartnerActivity)v92StopJoinedTracking()};
}
async function v92StartJoinedTracking(){if(v92JoinedWatch||v92JoinedNativeWatch||!joinedPartnerActivity)return;v92JoinedPoints=[];const saved=await get('activeTracking','joined-v92').catch(()=>null);if(saved?.activityUid===joinedPartnerActivity.activityUid)v92JoinedPoints=saved.points||[];const accept=loc=>v92JoinedPosition({latitude:loc.latitude,longitude:loc.longitude,accuracy:loc.accuracy,altitude:loc.altitude,speed:loc.speed},loc.time||now());if(nativeBridgeAvailable())try{v92JoinedNativeWatch=await window.WalkMemoryNative.start(accept,e=>updateSharedActivityUI(`Partner GPS: ${e?.message||e}`,true));updateSharedActivityUI('Connected · both phones are contributing ETA-quality GPS.');return}catch{}if(navigator.geolocation)v92JoinedWatch=navigator.geolocation.watchPosition(p=>accept({...p.coords}),e=>updateSharedActivityUI(`Partner GPS: ${e.message}`,true),{enableHighAccuracy:true,maximumAge:1000,timeout:20000})}
async function v92JoinedPosition(coords,timestamp){const p={lat:Number(coords.latitude),lon:Number(coords.longitude),t:Number(timestamp||now()),accuracy:Number(coords.accuracy||9999),altitude:coords.altitude==null?null:Number(coords.altitude),speed:coords.speed==null?null:Number(coords.speed)};if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon)||p.accuracy>(joinedPartnerActivity?.type==='drive'?50:30))return;const last=v92JoinedPoints.at(-1);if(last){const sec=(p.t-last.t)/1000,d=dist(last,p),limit=joinedPartnerActivity?.type==='drive'?70:4;if(sec<=0||sec>180||d/sec>limit)return}v92JoinedPoints.push(p);if(v92JoinedPoints.length>12000)v92JoinedPoints=v92JoinedPoints.slice(-12000);await put('activeTracking',{id:'joined-v92',uid:'joined-v92',activityUid:joinedPartnerActivity.activityUid,points:v92JoinedPoints,updatedAt:now()});if(now()-v92JoinedLastSent>5000){v92JoinedLastSent=now();authFetch('/api/shared-activity/location',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)}).catch(()=>{})}updateSharedActivityUI(`Connected · your phone contributed ${v92JoinedPoints.length} ETA-quality GPS points.`)}
async function v92StopJoinedTracking(){if(v92JoinedWatch!=null){navigator.geolocation.clearWatch(v92JoinedWatch);v92JoinedWatch=null}if(v92JoinedNativeWatch!=null&&window.WalkMemoryNative?.stop){try{await window.WalkMemoryNative.stop(v92JoinedNativeWatch)}catch{}v92JoinedNativeWatch=null}v92JoinedPoints=[];remove('activeTracking','joined-v92').catch(()=>{})}

function v92InstallSharedPlans(){$('v92SharePlan').onclick=v92ShareCurrentPlan;$('v92RefreshPlans').onclick=v92RefreshSharedPlans;const baseSave=v9SavePlan;v9SavePlan=async function(){await baseSave();if(v92SharedActive)await v92ShareCurrentPlan(true)};$('v9Save').onclick=v9SavePlan}
async function v92ShareCurrentPlan(silent=false){if(!settings.token||!partner)return alert('Sign in and link your partner first.');if(!v9Route)return alert('Create a route before sharing it.');if(!v9CurrentPlanUid)await v9SavePlan();const local=(await all('plans')).find(p=>p.uid===v9CurrentPlanUid);if(!local)return;const existing=v92SharedPlans.find(p=>p.uid===local.uid),body={plan:{...local,etaSource:settings.etaSource},baseRevision:existing?.revision};try{const r=await authFetch('/api/shared-plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});v92SharedActive=r.plan;await v92RefreshSharedPlans();if(!silent)v8Toast('Shared plan updated for both phones.')}catch(e){if(e.status===409)await v92RefreshSharedPlans();if(!silent)alert(e.message);else throw e}}
async function v92RefreshSharedPlans(){const box=$('v92SharedPlans');if(!box)return;if(!settings.token||!partner){box.innerHTML='<p class="muted">Link a partner to collaborate on plans.</p>';return}try{const r=await authFetch('/api/shared-plans');v92SharedPlans=r.plans||[];box.innerHTML=v92SharedPlans.length?v92SharedPlans.sort((a,b)=>b.updatedAt-a.updatedAt).map((p,i)=>`<div class="v92-shared-row"><div><b>${esc(p.name)}</b><small>${esc((p.mode||'walk').toUpperCase())} · ${(p.stops||[]).length} stops · revision ${p.revision} · ${p.updatedBy===account?.id?'you':esc(partner?.displayName||'partner')}</small></div><button data-v92-open-plan="${i}">OPEN</button><button data-v92-delete-plan="${i}">×</button></div>`).join(''):'<p class="muted">No shared plans yet.</p>';box.querySelectorAll('[data-v92-open-plan]').forEach(b=>b.onclick=()=>v92OpenSharedPlan(v92SharedPlans[Number(b.dataset.v92OpenPlan)]));box.querySelectorAll('[data-v92-delete-plan]').forEach(b=>b.onclick=()=>v92DeleteSharedPlan(v92SharedPlans[Number(b.dataset.v92DeletePlan)]));v92SetSyncState('online')}catch(e){box.innerHTML=`<p class="muted">Shared plans queued until the updated server is available: ${esc(e.message)}</p>`}}
async function v92OpenSharedPlan(plan){v92SharedActive=plan;await v9LoadPlan({...plan,uid:plan.uid});if(['mine','partner','both'].includes(plan.etaSource))await v92SetEtaSource(plan.etaSource);v8Toast(`Opened shared plan revision ${plan.revision}. Changes can update both phones.`)}
async function v92DeleteSharedPlan(plan){if(!confirm(`Remove shared plan “${plan.name}” for both phones?`))return;await authFetch('/api/shared-plan/delete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({uid:plan.uid})});if(v92SharedActive?.uid===plan.uid)v92SharedActive=null;await v92RefreshSharedPlans()}

function v92InstallMemories(){
  const baseData=v82MemoryData;v82MemoryData=async function(owner){const data=await baseData(owner);if(owner!=='both'||!data)return data;const shared=new Map(),walks=[];for(const w of data.walks||[]){if(!w.sharedActivityUid){walks.push(w);continue}const old=shared.get(w.sharedActivityUid);if(!old||w._owner==='mine')shared.set(w.sharedActivityUid,w)}return{...data,walks:[...walks,...shared.values()]}};
  const baseOpen=openWalk;openWalk=async function(walkUid,owner='mine'){await baseOpen(walkUid,owner);const data=owner==='partner'?partnerSnapshot:await localSnapshot(),walk=(data?.walks||[]).find(w=>w.uid===walkUid);if(!walk)return;const contributors=walk.contributors||[],$summary=$('walkVisitSummary');if(contributors.length)$summary?.insertAdjacentHTML('beforebegin',`<div class="v92-contributors"><b>Joint memory</b><br>${contributors.map(c=>esc(c.name||'Participant')).join(' + ')}${walk.sharedActivityUid?`<div class="button-row"><button id="v92RenameMemory">RENAME</button><button id="v92CommentMemory">COMMENT</button><button id="v92DeleteMemory">DELETE</button></div>`:''}${(walk.comments||[]).length?`<div>${walk.comments.map(c=>`<small><b>${esc(c.by||'Participant')}:</b> ${esc(c.text)}</small>`).join('<br>')}</div>`:''}</div>`);if(walk.sharedActivityUid){$('v92RenameMemory').onclick=()=>v92EditSharedMemory(walk,owner,'rename');$('v92CommentMemory').onclick=()=>v92EditSharedMemory(walk,owner,'comment');$('v92DeleteMemory').onclick=()=>v92EditSharedMemory(walk,owner,'delete')}const notes=(data?.voiceNotes||[]).filter(n=>n.activityUid===walk.uid&&/^data:audio\//i.test(n.audio||''));if(notes.length)$('walkPhotoGallery')?.insertAdjacentHTML('beforeend',`<div style="grid-column:1/-1"><b>Shared voice notes</b>${notes.map(n=>`<audio controls preload="metadata" src="${n.audio}"></audio>`).join('')}</div>`)};
}

async function v92EditSharedMemory(walk,owner,action){
  if(!settings.token)return alert('Sign in and sync with your partner to change a joint memory.');
  const body={uid:walk.uid,sharedActivityUid:walk.sharedActivityUid,action};
  if(action==='rename'){const title=prompt('Name this joint memory:',walk.title||activityLabel(walk));if(title==null)return;body.title=title.trim();if(!body.title)return alert('Enter a name.')}else if(action==='comment'){const text=prompt('Add a comment for both of you:','');if(text==null)return;body.text=text.trim();if(!body.text)return alert('Enter a comment.')}else if(!confirm(`Delete “${walk.title||activityLabel(walk)}” from both phones? This cannot be undone.`))return;
  try{
    const result=await authFetch('/api/shared-memory',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),changed=result.walk;
    if(owner==='partner'){
      const rows=[...(partnerSnapshot?.walks||[])],i=rows.findIndex(w=>w.uid===walk.uid||w.sharedActivityUid===walk.sharedActivityUid);if(i>=0){if(action==='delete')rows.splice(i,1);else rows[i]=changed}partnerSnapshot={...partnerSnapshot,walks:rows};
    }else{
      const local=(await all('walks')).find(w=>w.uid===walk.uid||w.sharedActivityUid===walk.sharedActivityUid);if(local){if(action==='delete'){await remove('walks',local.id);for(const row of await all('photos'))if(row.activityUid===local.uid)await remove('photos',row.id);for(const row of await all('visits'))if(row.walkUid===local.uid)await remove('visits',row.id)}else await put('walks',{...changed,id:local.id})}
    }
    closeModal('walkModal');await renderLists();await renderMap();v9RouteModels={walk:null,drive:null};await rebuildEtaProfile();v8Toast(action==='delete'?'Joint memory deleted.':action==='comment'?'Comment shared.':'Joint memory renamed.');
  }catch(e){alert(e.status===404?'Joint-memory editing is ready in the app, but the V9.2 partner server still needs to be published. No data was changed.':e.message)}
}

function v92InstallAccountTools(){
  $('v92CopyPair').onclick=async()=>{if(!account?.inviteCode)return alert('Sign in first.');const value=`nights://pair/${account.inviteCode}`;try{await navigator.clipboard.writeText(value);v8Toast('Pairing link copied.')}catch{prompt('Copy pairing link:',value)}};
  $('v92LandmarkApproval').checked=!!settings.landmarkApproval;$('v92LandmarkApproval').onchange=async()=>{settings.landmarkApproval=$('v92LandmarkApproval').checked;saveSettings();if(settings.token)try{await authFetch('/api/account/sharing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({routes:settings.partnerRoutes!==false,photos:settings.partnerPhotos!==false,landmarks:settings.partnerLandmarks!==false,plans:settings.partnerPlans!==false,landmarkApproval:settings.landmarkApproval})});v8Toast('Partner landmark approval setting saved.')}catch(e){alert(e.message)}};
  v92RenderPairing();
}
function v92RenderPairing(){const el=$('v92PairCard');if(el)el.textContent=account?.inviteCode?`NIGHTS · ${account.inviteCode}`:'SIGN IN FIRST'}
async function v92RegisterDevice(){if(!settings.token)return;let deviceId=localStorage.getItem('nightsV92DeviceId');if(!deviceId){deviceId=uid();localStorage.setItem('nightsV92DeviceId',deviceId)}await authFetch('/api/device/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deviceId,name:navigator.userAgent.includes('Android')?'Android phone':'Nights device',platform:navigator.userAgent.includes('Android')?'android':'web',appVersion:'9.4.1'})});await v92RenderDevices()}
async function v92RenderDevices(){const box=$('v92Devices');if(!box||!settings.token)return;try{const r=await authFetch('/api/devices');box.innerHTML=(r.devices||[]).map(d=>`<div class="v92-device"><span><b>${esc(d.name)}</b><br><small>V${esc(d.appVersion||'?')} · ${new Date(d.lastSeen).toLocaleString()}</small></span><button data-v92-device="${esc(d.deviceId)}">REMOVE</button></div>`).join('')||'<p class="muted">No registered devices.</p>';box.querySelectorAll('[data-v92-device]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this device from the account list? Local data on it will remain.'))return;await authFetch('/api/device/remove',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({deviceId:b.dataset.v92Device})});v92RenderDevices()})}catch(e){box.innerHTML=`<p class="muted">Device list needs the V9.2 partner server: ${esc(e.message)}</p>`}}
async function v92RefreshApprovals(){const box=$('v92Approvals');if(!box||!settings.token)return;try{const r=await authFetch('/api/landmark-approvals'),rows=r.approvals||[];box.innerHTML=rows.map(a=>`<div class="v92-approval"><b>${esc(a.fromName)} wants to change ${esc(a.landmark?.name||'a landmark')}</b><div class="button-row"><button data-v92-approve="${esc(a.id)}" class="primary">APPROVE</button><button data-v92-reject="${esc(a.id)}">REJECT</button></div></div>`).join('');box.querySelectorAll('[data-v92-approve]').forEach(b=>b.onclick=()=>v92ResolveApproval(b.dataset.v92Approve,true));box.querySelectorAll('[data-v92-reject]').forEach(b=>b.onclick=()=>v92ResolveApproval(b.dataset.v92Reject,false))}catch{box.innerHTML=''}}
async function v92ResolveApproval(id,accept){await authFetch('/api/landmark-approval',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,accept})});await cloudPull();await v92RefreshApprovals();v8Toast(accept?'Landmark change approved.':'Landmark change rejected.')}
