/* Nights v8 enhancement layer. Loaded before app.js and activated after boot. */
let v8Paused=false,v8SelectedWalk=null,v8SelectedOwner='mine',v8PlaybackTimer=null,v8MapLayer=null,v8PartnerMarker=null,v8HeatLayer=null,v8PlanLayer=null,v8LastDelete=null,v8Recording=null,v8StopAnchor=null,v8StopSince=0,v8LastSuggestion=0,v8Initialized=false;
const V8_MAPS={street:{label:'Street',url:'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',subdomains:'abc',maxZoom:19,attribution:'© OpenStreetMap contributors'},dark:{label:'Dark',url:'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',subdomains:'abc',maxZoom:19,attribution:'© OpenStreetMap contributors',filter:'invert(1) hue-rotate(180deg) brightness(.82) contrast(.95)'},terrain:{label:'Terrain',url:'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',subdomains:'abc',maxZoom:17,attribution:'© OpenStreetMap, SRTM'},satellite:{label:'Satellite',url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',subdomains:'',maxZoom:19,attribution:'© Esri'}};

window.addEventListener('nights-ready',v8Start);
window.addEventListener('load',()=>{let attempts=0;const timer=setInterval(()=>{attempts++;if((typeof db!=='undefined'&&db)||attempts>60){clearInterval(timer);if(typeof db!=='undefined'&&db)v8Start()}},250)});

function v8Start(){if(v8Initialized)return;v8Initialized=true;v8Init().catch(e=>{v8Initialized=false;console.error('Nights enhancements:',e)})}

async function v8Init(){
  v8Styles();v8BuildUI();v8WrapTracking();v8WrapLandmarks();v8WrapMemories();v8WrapPartner();v8Bind();
  try{await v8AutoBackup()}catch(e){console.warn('Automatic backup deferred:',e)}await v8RenderTrash();await v8RenderSyncHistory();await renderLists();await renderMemories();
  v8ApplyTheme();v8LoadCategories();v8UpdateNetwork();if(settings.mapStyle&&$('v8MapStyle')){$('v8MapStyle').value=settings.mapStyle;v8SwitchMap()}v8HandleQuickAction();
}

function v8Styles(){
  const s=document.createElement('style');s.textContent=`
  .v8-tools{display:flex;gap:7px;flex-wrap:wrap;align-items:center;margin:10px 0}.v8-tools input,.v8-tools select{min-width:120px;flex:1}.v8-badge{padding:4px 8px;border:1px solid #777;border-radius:12px;font-size:12px}.v8-good{color:#0a7b37}.v8-warn{color:#a65d00}.v8-danger{color:#b00020}.v8-favorite{color:#d59b00}.v8-panel{margin-top:12px}.v8-action-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:7px;margin:10px 0}.v8-action-grid button{width:100%}.v8-hidden{display:none!important}.v8-toast{position:fixed;left:50%;bottom:80px;transform:translateX(-50%);z-index:99999;background:#202020;color:#fff;padding:12px 16px;border-radius:8px;box-shadow:0 4px 18px #0008}.v8-gps{height:8px;background:#aaa4;border-radius:8px;overflow:hidden;margin:7px auto;max-width:360px}.v8-gps>i{display:block;height:100%;width:0;background:#1c9c4b;transition:.2s}.v8-high-contrast{filter:contrast(1.25)}body.v8-large button,body.v8-large input,body.v8-large select{min-height:48px;font-size:17px}body.v8-reduce-motion *{animation:none!important;transition:none!important}.v8-photo-private{opacity:.55;outline:3px solid #777}.v8-calendar{max-width:220px}.v8-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:8px}.v8-summary .window-card{text-align:center}.v8-summary b{font-size:24px;display:block}.v8-trash-row{display:flex;justify-content:space-between;gap:8px;align-items:center}.v8-route-dot{width:13px;height:13px;border-radius:50%;display:inline-block;margin-right:5px}`;document.head.appendChild(s);
}

function v8BuildUI(){
  document.querySelector('.brand small').textContent='V8.1';
  const mapTitle=$('map')?.querySelector('.panel-title');mapTitle?.insertAdjacentHTML('afterend',`<div class="v8-tools" id="v8MapTools"><select id="v8MapStyle"><option value="street">Street map</option><option value="dark">Dark map</option><option value="terrain">Terrain map</option><option value="satellite">Satellite</option></select><button id="v8OfflineMap">SAVE ALL MAPS OFFLINE</button><button id="v8PlanRoute">PLAN LANDMARK ROUTE</button><button id="v8Breadcrumb">BACK TO START</button><button id="v8Heat">EXPLORATION HEAT MAP</button></div>`);
  $('gpsDetail')?.insertAdjacentHTML('afterend','<div class="v8-gps" title="GPS quality"><i id="v8GpsBar"></i></div>');
  $('start')?.parentElement?.insertAdjacentHTML('beforeend','<button id="v8Pause" disabled>PAUSE</button>');
  $('sharedActivityStatus')?.insertAdjacentHTML('afterend','<div id="v8PartnerLive" class="v8-badge">Partner live location: waiting</div>');
  $('landmarks')?.querySelector('.panel-title')?.insertAdjacentHTML('afterend',`<div class="v8-tools"><input id="v8LandmarkSearch" type="search" placeholder="Search landmarks, notes, categories"><select id="v8LandmarkSort"><option value="distance">Nearest</option><option value="name">Name</option><option value="rating">Rating</option><option value="visits">Most visited</option><option value="newest">Newest</option><option value="last">Last visited</option></select><label class="checkline"><input id="v8FavoritesOnly" type="checkbox"> Favorites only</label><button id="v8FindDuplicates">FIND DUPLICATES</button><button id="v8ManageCategories">MANAGE CATEGORIES</button><button id="v8Collection">SHARED COLLECTION</button></div><div id="v8LandmarkSuggestion" class="notice hidden"></div>`);
  $('currentActivityPhotos')?.insertAdjacentHTML('beforebegin','<div class="v8-tools"><button id="v8DuplicatePhotos">FIND DUPLICATE PHOTOS</button></div>');
  $('statsGrid')?.insertAdjacentHTML('beforebegin',`<div class="v8-tools"><input id="v8MemoryDate" class="v8-calendar" type="month"><button id="v8ClearDate">ALL DATES</button><button id="v8Compare">COMPARE / COMBINE</button></div><div id="v8Insights" class="v8-summary"></div>`);
  $('walkVisitSummary')?.insertAdjacentHTML('beforebegin',`<div id="v8WalkActions" class="v8-action-grid"><button id="v8EditWalk">EDIT DETAILS</button><button id="v8TrimStart">TRIM START</button><button id="v8TrimEnd">TRIM END</button><button id="v8Playback">PLAY ROUTE</button><button id="v8Highlight">CREATE HIGHLIGHT</button><button id="v8Voice">VOICE NOTE</button><button id="v8Comment">COMMENT / REACT</button><button id="v8DeleteWalk" class="danger">DELETE WALK</button></div><div id="v8WalkExtra" class="muted"></div>`);
  $('walkPhotoGallery')?.insertAdjacentHTML('beforebegin','<p class="muted">Tap a photo to set its caption, tags, cover status, or privacy.</p>');
  const data=$('data');data?.querySelector('.danger-zone')?.insertAdjacentHTML('beforebegin',`<div class="window-card"><h2>Backup health</h2><div id="v8BackupHealth">Checking backups…</div><button id="v8BackupNow">BACK UP NOW</button></div><div class="window-card"><h2>Recently deleted</h2><p class="muted">Deleted activities can be restored here.</p><div id="v8Trash"></div></div><div class="window-card"><h2>Sync history</h2><div id="v8Network"></div><div id="v8SyncHistory"></div></div>`);
  $('settings')?.querySelector('.two-col')?.insertAdjacentHTML('afterend',`<div class="window-card"><h2>Accessibility & appearance</h2><label>Theme<select id="v8Theme"><option value="default">Nights red</option><option value="midnight">Midnight blue</option><option value="forest">Forest</option></select></label><label class="checkline"><input id="v8LargeControls" type="checkbox"> Larger controls</label><label class="checkline"><input id="v8HighContrast" type="checkbox"> High contrast</label><label class="checkline"><input id="v8ReduceMotion" type="checkbox"> Reduce motion</label><label>Route color<input id="v8RouteColor" type="color" value="${safeColor(settings.routeColor||account?.walkColor,'#d00000')}"></label></div><div class="window-card"><h2>Partner sharing permissions</h2><label class="checkline"><input id="v8SharePrecise" type="checkbox"> Share precise live position</label><label class="checkline"><input id="v8ShareRoutes" type="checkbox"> Share saved routes</label><label class="checkline"><input id="v8SharePhotos" type="checkbox"> Share activity photos</label><label class="checkline"><input id="v8ShareLandmarks" type="checkbox"> Share landmarks</label><label class="checkline"><input id="v8SharePlans" type="checkbox"> Share plans and collections</label></div>`);
  const lmDialog=$('landmarkModal')?.querySelector('.dialog');lmDialog?.querySelector('form')?.insertAdjacentHTML('beforeend','<div class="v8-tools"><button id="v8LandmarkHistory" type="button">VISIT HISTORY</button><button id="v8FavoriteLandmark" type="button">☆ FAVORITE</button></div>');
  $('lmRadius')?.parentElement?.insertAdjacentHTML('afterend','<label>Additional detection zones (feet, comma separated)<input id="v8LmZones" inputmode="numeric" placeholder="50, 150, 300"></label>');
}

function v8Bind(){
  $('v8Pause').onclick=v8TogglePause;$('v8MapStyle').onchange=v8SwitchMap;$('v8OfflineMap').onclick=v8SaveOffline;$('v8PlanRoute').onclick=v8PlanRoute;$('v8Breadcrumb').onclick=v8Breadcrumb;$('v8Heat').onclick=v8ToggleHeat;
  ['v8LandmarkSearch','v8LandmarkSort','v8FavoritesOnly'].forEach(id=>$(id).addEventListener(id==='v8LandmarkSearch'?'input':'change',()=>renderLists()));
  $('v8FindDuplicates').onclick=v8FindDuplicates;$('v8ManageCategories').onclick=v8ManageCategories;$('v8Collection').onclick=v8Collection;$('v8DuplicatePhotos').onclick=v8DuplicatePhotos;$('v8MemoryDate').onchange=()=>renderMemories();$('v8ClearDate').onclick=()=>{$('v8MemoryDate').value='';renderMemories()};$('v8Compare').onclick=v8Compare;
  $('v8EditWalk').onclick=v8EditWalk;$('v8TrimStart').onclick=()=>v8Trim('start');$('v8TrimEnd').onclick=()=>v8Trim('end');$('v8Playback').onclick=v8Playback;$('v8Highlight').onclick=v8Highlight;$('v8Voice').onclick=v8Voice;$('v8Comment').onclick=v8Comment;$('v8DeleteWalk').onclick=v8DeleteWalk;
  $('v8BackupNow').onclick=()=>v8CreateBackup(true);$('v8LandmarkHistory').onclick=v8LandmarkHistory;$('v8FavoriteLandmark').onclick=v8FavoriteCurrent;
  ['v8Theme','v8LargeControls','v8HighContrast','v8ReduceMotion','v8RouteColor','v8SharePrecise','v8ShareRoutes','v8SharePhotos','v8ShareLandmarks','v8SharePlans'].forEach(id=>$(id).addEventListener('change',v8SaveSettings));
  window.addEventListener('online',()=>{v8UpdateNetwork();v8LogSync('Connection restored; pending changes will sync.');scheduleCloudSync()});window.addEventListener('offline',()=>{v8UpdateNetwork();v8LogSync('Offline; changes are safely queued on this phone.')});
  window.addEventListener('nights-tracking-control',e=>{if(e.detail==='pause')v8TogglePause();if(e.detail==='stop'&&currentWalkUid)stopTracking()});
}

function v8WrapTracking(){
  const baseAccept=acceptPosition;acceptPosition=async function(coords,timestamp){const accuracy=Number(coords.accuracy??9999),bar=$('v8GpsBar');if(bar){bar.style.width=`${Math.max(5,Math.min(100,100-accuracy))}%`;bar.style.background=accuracy<=20?'#159447':accuracy<=60?'#d99a00':'#bd2020'}if(v8Paused)return;await baseAccept(coords,timestamp);v8WatchForStop()};
  const baseStart=startTracking;startTracking=async function(){await baseStart();if(currentWalkUid){$('v8Pause').disabled=false;v8Paused=false;$('v8Pause').textContent='PAUSE'}};$('start').onclick=startTracking;
  const baseStop=stopTracking;stopTracking=async function(){v8Paused=false;$('v8Pause').disabled=true;await baseStop()};$('stop').onclick=stopTracking;
}
function v8TogglePause(){if(!currentWalkUid)return;v8Paused=!v8Paused;$('v8Pause').textContent=v8Paused?'RESUME':'PAUSE';$('state').textContent=v8Paused?'PAUSED':`TRACKING ${currentActivityType.toUpperCase()}`;checkpointTracking()}
function v8WatchForStop(){if(!lastPoint||!currentWalkUid)return;if(!v8StopAnchor){v8StopAnchor=lastPoint;v8StopSince=now();return}if(dist(v8StopAnchor,lastPoint)>25){v8StopAnchor=lastPoint;v8StopSince=now();return}if(now()-v8StopSince>300000&&now()-v8LastSuggestion>900000){v8LastSuggestion=now();const box=$('v8LandmarkSuggestion');box.textContent='You have stayed near one place for 5 minutes. Tap here to save it as a landmark.';box.classList.remove('hidden');box.onclick=()=>{showPage('landmarks');openLandmarkEditor({lat:lastPoint.lat,lon:lastPoint.lon,name:'Suggested stop',category:'Other',radius:feetToMeters(100),photos:[]},null);box.classList.add('hidden')}}}

function v8WrapLandmarks(){
  const baseRender=renderLists;renderLists=async function(){await baseRender();await v8FilterSortLandmarks()};$('categoryFilter').onchange=()=>renderLists();$('subcategoryFilter').onchange=()=>renderLists();
  const baseOpen=openLandmarkEditor;openLandmarkEditor=function(l,id){baseOpen(l,id);setTimeout(()=>{$('v8FavoriteLandmark').textContent=l.favorite?'★ FAVORITE':'☆ FAVORITE';$('v8LmZones').value=(l.zonesFeet||[]).join(', ')},0)};
  const baseSave=saveLandmark;saveLandmark=async function(e){const zones=($('v8LmZones')?.value||'').split(',').map(Number).filter(x=>Number.isFinite(x)&&x>0);if(zones.length)$('lmRadius').value=String(Math.max(Number($('lmRadius').value)||1,...zones));const name=$('lmName').value.trim(),lat=Number($('lmLat').value),lon=Number($('lmLon').value);await baseSave(e);const saved=(await all('landmarks')).filter(l=>l.name===name&&Math.abs(l.lat-lat)<1e-7&&Math.abs(l.lon-lon)<1e-7).sort((a,b)=>Number(b.updatedAt)-Number(a.updatedAt))[0];if(saved){saved.zonesFeet=zones;saved.updatedAt=now();await put('landmarks',saved);scheduleCloudSync()}};$('lmForm').onsubmit=saveLandmark;
  const baseCheck=checkLandmarks;checkLandmarks=async function(p,w){const before=(await all('visits')).length;await baseCheck(p,w);const visits=await all('visits');if(visits.length>before){const visit=visits.sort((a,b)=>b.date-a.date)[0],lm=(await all('landmarks')).find(x=>x.uid===visit.landmarkUid);if(lm){v8Notify(`Arrived at ${lm.name}`);if(settings.token&&sharedHostActive)authFetch('/api/shared-activity/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event:'landmark-arrival',message:`${account?.displayName||'Your partner'} arrived at ${lm.name}.`})}).catch(()=>{})}}};
}
async function v8FilterSortLandmarks(){
  const q=($('v8LandmarkSearch')?.value||'').trim().toLowerCase(),fav=$('v8FavoritesOnly')?.checked,sort=$('v8LandmarkSort')?.value||'distance',landmarks=await all('landmarks'),visits=await all('visits'),byId=new Map(landmarks.map(x=>[String(x.id),x]));
  const list=$('landmarkList'),cards=[...list.querySelectorAll('[data-landmark-id]')];cards.forEach(card=>{const l=byId.get(card.dataset.landmarkId),text=[l?.name,l?.category,l?.subcategory,l?.desc,l?.notes].join(' ').toLowerCase();card.classList.toggle('v8-hidden',!!(q&&!text.includes(q))||!!(fav&&!l?.favorite));if(l&&!card.querySelector('.v8-fav-button')){const b=document.createElement('button');b.className='v8-fav-button';b.textContent=l.favorite?'★':'☆';b.title='Favorite';b.onclick=async e=>{e.stopPropagation();l.favorite=!l.favorite;l.updatedAt=now();await put('landmarks',l);scheduleCloudSync();renderLists()};card.appendChild(b)}});
  const score=l=>sort==='name'?(l.name||'').toLowerCase():sort==='rating'?-Number(l.rating||0):sort==='visits'?-visits.filter(v=>v.landmarkUid===l.uid).length:sort==='newest'?-Number(l.updatedAt||0):sort==='last'?-Math.max(0,...visits.filter(v=>v.landmarkUid===l.uid).map(v=>v.date||0)):0;
  cards.sort((a,b)=>{const x=score(byId.get(a.dataset.landmarkId)),y=score(byId.get(b.dataset.landmarkId));return typeof x==='string'?x.localeCompare(y):x-y}).forEach(c=>list.appendChild(c));
}
async function v8FavoriteCurrent(){if(!editingLandmarkId)return;const l=await get('landmarks',editingLandmarkId);l.favorite=!l.favorite;l.updatedAt=now();await put('landmarks',l);$('v8FavoriteLandmark').textContent=l.favorite?'★ FAVORITE':'☆ FAVORITE';scheduleCloudSync()}
async function v8LandmarkHistory(){if(!editingLandmarkId)return;const l=await get('landmarks',editingLandmarkId),visits=(await all('visits')).filter(v=>v.landmarkUid===l.uid).sort((a,b)=>b.date-a.date);alert(visits.length?`${l.name} visits:\n\n${visits.map(v=>new Date(v.date).toLocaleString()).join('\n')}`:`No recorded visits to ${l.name} yet.`)}
async function v8FindDuplicates(){const ls=await all('landmarks'),pairs=[];for(let i=0;i<ls.length;i++)for(let j=i+1;j<ls.length;j++)if(dist(ls[i],ls[j])<40||String(ls[i].name).toLowerCase()===String(ls[j].name).toLowerCase())pairs.push(`${ls[i].name} ↔ ${ls[j].name}`);alert(pairs.length?`Possible duplicates:\n\n${pairs.join('\n')}`:'No likely duplicate landmarks found.')}
function v8ManageCategories(){const cats=prompt('Custom categories, separated by commas:',(settings.customCategories||[]).join(', '));if(cats===null)return;const subs=prompt('Custom subcategories, separated by commas:',(settings.customSubcategories||[]).join(', '));if(subs===null)return;settings.customCategories=cats.split(',').map(x=>x.trim()).filter(Boolean);settings.customSubcategories=subs.split(',').map(x=>x.trim()).filter(Boolean);saveSettings();$('categoryOptions').innerHTML=settings.customCategories.map(x=>`<option value="${esc(x)}">`).join('');$('subcategoryOptions').innerHTML=settings.customSubcategories.map(x=>`<option value="${esc(x)}">`).join('');alert('Custom category suggestions saved. Existing landmark categories remain available too.')}
function v8LoadCategories(){if(settings.customCategories?.length)$('categoryOptions').innerHTML=settings.customCategories.map(x=>`<option value="${esc(x)}">`).join('');if(settings.customSubcategories?.length)$('subcategoryOptions').innerHTML=settings.customSubcategories.map(x=>`<option value="${esc(x)}">`).join('')}
async function v8Collection(){const ls=await all('landmarks'),existing=await all('collections'),mode=prompt(`Type NEW to create a shared landmark collection, or VIEW to list collections.\n\nExisting: ${existing.map(x=>x.name).join(', ')||'none'}`,'NEW');if(!mode)return;if(mode.toUpperCase()==='VIEW'){const partnerCollections=partnerSnapshot?.collections||[];return alert(`My collections:\n${existing.map(x=>`${x.name}: ${x.landmarkUids.length} places`).join('\n')||'None'}\n\nPartner collections:\n${partnerCollections.map(x=>`${x.name}: ${x.landmarkUids.length} places`).join('\n')||'None'}`)}const name=prompt('Collection name:','Places to visit');if(!name)return;const names=prompt(`Landmark names separated by commas:\n\n${ls.map(x=>x.name).join(', ')}`);if(!names)return;const chosen=names.split(',').map(n=>ls.find(l=>l.name.toLowerCase()===n.trim().toLowerCase())).filter(Boolean);if(!chosen.length)return alert('No matching landmarks selected.');await put('collections',{uid:uid(),name,landmarkUids:chosen.map(x=>x.uid),createdAt:now(),updatedAt:now()});scheduleCloudSync();alert(`Saved “${name}” with ${chosen.length} places.`)}
async function v8DuplicatePhotos(){const ps=await all('photos'),groups=[];for(let i=0;i<ps.length;i++)for(let j=i+1;j<ps.length;j++)if(ps[i].image===ps[j].image||(`${ps[i].image?.length}:${ps[i].image?.slice(-80)}`===`${ps[j].image?.length}:${ps[j].image?.slice(-80)}`))groups.push(`${new Date(ps[i].date).toLocaleString()} ↔ ${new Date(ps[j].date).toLocaleString()}`);alert(groups.length?`Possible duplicate photos:\n\n${groups.join('\n')}`:'No duplicate activity photos found.')}

function v8WrapMemories(){
  const baseRender=renderMemories;renderMemories=async function(){await baseRender();await v8EnhanceMemories()};
  const baseOpen=openWalk;openWalk=async function(uidValue,owner='mine'){await baseOpen(uidValue,owner);v8SelectedWalk=uidValue;v8SelectedOwner=owner;await v8ShowWalkExtra();$('v8WalkActions').classList.toggle('v8-hidden',owner!=='mine');v8BindPhotoTools()};
}
async function v8EnhanceMemories(){
  const owner=$('memoryOwner').value,d=owner==='partner'?partnerSnapshot:await localSnapshot(),allWalks=[...(d?.walks||[])],month=$('v8MemoryDate')?.value,walks=month?allWalks.filter(w=>new Date(w.date).toISOString().slice(0,7)===month):allWalks;
  if(month)document.querySelectorAll('#walkList [data-walk-uid]').forEach(el=>{const w=allWalks.find(x=>x.uid===el.dataset.walkUid);el.classList.toggle('v8-hidden',!w||new Date(w.date).toISOString().slice(0,7)!==month)});
  const longest=[...walks].sort((a,b)=>Number(b.distance)-Number(a.distance))[0],fastest=[...walks].filter(w=>w.duration>0).sort((a,b)=>(b.distance/b.duration)-(a.distance/a.duration))[0],elev=[...walks].sort((a,b)=>elevationStats(b).gain-elevationStats(a).gain)[0],areas=new Set(walks.flatMap(w=>(w.points||[]).map(p=>`${Number(p.lat).toFixed(2)},${Number(p.lon).toFixed(2)}`))).size,latest=[...walks].sort((a,b)=>b.date-a.date)[0],pastCells=new Set(walks.filter(w=>w!==latest).flatMap(w=>(w.points||[]).map(p=>`${Number(p.lat).toFixed(3)},${Number(p.lon).toFixed(3)}`))),latestCells=new Set((latest?.points||[]).map(p=>`${Number(p.lat).toFixed(3)},${Number(p.lon).toFixed(3)}`)),newPct=latestCells.size?Math.round([...latestCells].filter(x=>!pastCells.has(x)).length/latestCells.size*100):0,visitDays=[...new Set((d?.visits||[]).map(v=>new Date(v.date).toISOString().slice(0,10)))].sort().reverse();let streak=0,day=new Date();for(const key of visitDays){const expected=day.toISOString().slice(0,10);if(key!==expected){if(!streak&&key===new Date(day-86400000).toISOString().slice(0,10)){day=new Date(day-86400000)}else break}streak++;day=new Date(day-86400000)}const photos=d?.photos||[],sharedMs=walks.filter(w=>photos.some(p=>p.activityUid===w.uid&&p.contributorName)).reduce((s,w)=>s+Number(w.duration||0),0),months={};for(const w of walks){const k=new Date(w.date).toISOString().slice(0,7);months[k]=(months[k]||0)+Number(w.distance||0)}const trend=Object.entries(months).sort().slice(-6),trendMax=Math.max(1,...trend.map(x=>x[1]));
  $('v8Insights').innerHTML=`<div class="window-card"><b>${walks.length}</b>activities${month?' this month':''}</div><div class="window-card"><b>${longest?mi(longest.distance):'0.00'} mi</b>longest</div><div class="window-card"><b>${fastest?mi(fastest.distance):'—'}</b>fastest activity distance</div><div class="window-card"><b>${elev?Math.round(elevationStats(elev).gain*3.28084):0} ft</b>most climbing</div><div class="window-card"><b>${areas}</b>map areas explored</div><div class="window-card"><b>${newPct}%</b>new area on latest route</div><div class="window-card"><b>${streak} days</b>landmark streak</div><div class="window-card"><b>${ft(sharedMs)}</b>shared activity time</div><div class="window-card" style="grid-column:1/-1"><b>Distance trend</b><div style="display:flex;align-items:end;height:100px;gap:6px">${trend.map(([k,v])=>`<span title="${k}: ${mi(v)} mi" style="flex:1;background:#b12222;height:${Math.max(5,v/trendMax*80)}px"><small>${k.slice(5)}</small></span>`).join('')}</div></div>`;
}
async function v8ShowWalkExtra(){const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk),notes=await all('voiceNotes');if(!w)return;$('v8WalkExtra').innerHTML=`${w.notes?`<b>Notes:</b> ${esc(w.notes)}<br>`:''}${w.tags?.length?`<b>Tags:</b> ${w.tags.map(esc).join(', ')}<br>`:''}${w.rating?`<b>Rating:</b> ${'★'.repeat(w.rating)}<br>`:''}${w.comments?.length?`<b>Comments:</b> ${w.comments.map(x=>esc(x.text||x)).join(' · ')}<br>`:''}<b>Voice notes:</b> ${notes.filter(n=>n.activityUid===w.uid).length}`}
async function v8EditWalk(){const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk);if(!w)return;w.title=prompt('Activity name:',w.title||activityLabel(w))||w.title;w.notes=prompt('Notes:',w.notes||'')??w.notes;w.tags=(prompt('Tags separated by commas:',(w.tags||[]).join(', '))??'').split(',').map(x=>x.trim()).filter(Boolean);const rating=Number(prompt('Rating from 0 to 5:',String(w.rating||0)));if(Number.isFinite(rating))w.rating=Math.max(0,Math.min(5,Math.round(rating)));w.updatedAt=now();await put('walks',w);scheduleCloudSync();await refreshAll();await openWalk(w.uid,'mine')}
function v8RouteDistance(ps){let d=0;for(let i=1;i<ps.length;i++)d+=dist(ps[i-1],ps[i]);return d}
async function v8Trim(side){const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk);if(!w||w.points.length<3)return;const count=Math.max(1,Number(prompt(`How many GPS points should be removed from the ${side}?`,'5'))||0);if(!count)return;w.points=side==='start'?w.points.slice(count):w.points.slice(0,-count);if(w.points.length<2)return alert('That would remove too much of the route.');w.distance=v8RouteDistance(w.points);w.date=w.points[0].t||w.date;w.duration=Math.max(0,(w.points.at(-1).t||w.date+w.duration)-w.date);w.updatedAt=now();await put('walks',w);scheduleCloudSync();await refreshAll();openWalk(w.uid,'mine')}
async function v8DeleteWalk(){const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk);if(!w||!confirm(`Move “${w.title||activityLabel(w)}” to Recently Deleted?`))return;const photos=(await all('photos')).filter(x=>x.activityUid===w.uid),visits=(await all('visits')).filter(x=>x.walkUid===w.uid),trash={kind:'walk',deletedAt:now(),walk:w,photos,visits};const trashId=await put('trash',trash);for(const x of photos)await remove('photos',x.id);for(const x of visits)await remove('visits',x.id);await remove('walks',w.id);v8LastDelete=trashId;closeModal('walkModal');scheduleCloudSync();await refreshAll();await v8RenderTrash();v8Toast('Activity moved to Recently Deleted.',true)}
async function v8RenderTrash(){if(!$('v8Trash'))return;const items=(await all('trash')).sort((a,b)=>b.deletedAt-a.deletedAt);$('v8Trash').innerHTML=items.length?items.map(x=>`<div class="window-card v8-trash-row"><span><b>${esc(x.walk?.title||x.landmark?.name||'Deleted item')}</b><br><small>${formatDate(x.deletedAt)}</small></span><span><button data-restore="${x.id}">RESTORE</button><button data-purge="${x.id}" class="danger">DELETE FOREVER</button></span></div>`).join(''):'<div class="muted">Recently Deleted is empty.</div>';document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>v8Restore(Number(b.dataset.restore)));document.querySelectorAll('[data-purge]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this permanently?')){await remove('trash',Number(b.dataset.purge));v8RenderTrash()}})}
async function v8Restore(id){const x=await get('trash',id);if(!x)return;if(x.kind==='walk'){const w={...x.walk};delete w.id;await upsertImported('walks',w);for(const p of x.photos||[]){const y={...p};delete y.id;await upsertImported('photos',y)}for(const v of x.visits||[]){const y={...v};delete y.id;await upsertImported('visits',y)}}await remove('trash',id);scheduleCloudSync();await refreshAll();v8RenderTrash();v8Toast('Restored.')}
function v8Toast(text,undo=false){document.querySelector('.v8-toast')?.remove();const x=document.createElement('div');x.className='v8-toast';x.innerHTML=`${esc(text)} ${undo?'<button id="v8Undo">UNDO</button>':''}`;document.body.appendChild(x);if(undo)$('v8Undo').onclick=()=>v8LastDelete&&v8Restore(v8LastDelete);setTimeout(()=>x.remove(),7000)}

async function v8Playback(){clearInterval(v8PlaybackTimer);const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk),ps=w?.points||[];if(!ps.length)return;let i=0;const marker=L.circleMarker([ps[0].lat,ps[0].lon],{radius:9,color:'#ffd400',fillOpacity:1}).addTo(walkModalLayer);v8PlaybackTimer=setInterval(()=>{i+=Math.max(1,Math.floor(ps.length/150));if(i>=ps.length){clearInterval(v8PlaybackTimer);return}marker.setLatLng([ps[i].lat,ps[i].lon]);walkModalMap.panTo([ps[i].lat,ps[i].lon],{animate:true})},100)}
async function v8Highlight(){const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk);if(!w)return;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1080;const c=canvas.getContext('2d'),grad=c.createLinearGradient(0,0,1080,1080);grad.addColorStop(0,'#190000');grad.addColorStop(1,'#650000');c.fillStyle=grad;c.fillRect(0,0,1080,1080);c.fillStyle='#fff';c.font='bold 74px sans-serif';c.fillText('NIGHTS',70,110);c.font='bold 55px sans-serif';c.fillText((w.title||activityLabel(w)).slice(0,28),70,230);c.font='42px sans-serif';c.fillText(`${mi(w.distance)} miles`,70,340);c.fillText(`${ft(w.duration)} duration`,70,410);c.fillText(`${w.points.length} GPS points`,70,480);c.fillText(new Date(w.date).toLocaleDateString(),70,550);c.strokeStyle=safeColor(settings.routeColor||account?.walkColor,'#ff3030');c.lineWidth=12;const ps=w.points||[];if(ps.length>1){const xs=ps.map(p=>p.lon),ys=ps.map(p=>p.lat),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);c.beginPath();ps.forEach((p,i)=>{const x=100+(p.lon-minX)/(maxX-minX||1)*880,y=950-(p.lat-minY)/(maxY-minY||1)*300;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}canvas.toBlob(async blob=>{const file=new File([blob],'nights-highlight.png',{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:w.title,files:[file]});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();URL.revokeObjectURL(a.href)}})}
async function v8Comment(){const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk);if(!w)return;const text=prompt('Add a comment or reaction:','❤️ ');if(!text)return;w.comments||=[];w.comments.push({text,date:now(),by:account?.displayName||'Me'});w.updatedAt=now();await put('walks',w);scheduleCloudSync();v8ShowWalkExtra()}
async function v8Compare(){const ws=(await all('walks')).sort((a,b)=>b.date-a.date);if(ws.length<2)return alert('You need at least two activities.');const menu=ws.slice(0,25).map((w,i)=>`${i+1}. ${w.title||activityLabel(w)} — ${formatDate(w.date)}`).join('\n'),a=Number(prompt(`Choose the first activity number:\n\n${menu}`)),b=Number(prompt(`Choose the second activity number:\n\n${menu}`));if(!ws[a-1]||!ws[b-1]||a===b)return;const x=ws[a-1],y=ws[b-1],choice=prompt(`Comparison\n\n${x.title}: ${mi(x.distance)} mi, ${ft(x.duration)}\n${y.title}: ${mi(y.distance)} mi, ${ft(y.duration)}\n\nType COMBINE to create one joined activity, or OK to close.`,'OK');if(String(choice).toUpperCase()==='COMBINE'){const ps=[...(x.points||[]),...(y.points||[])].sort((p,q)=>(p.t||0)-(q.t||0)),date=Math.min(x.date,y.date),end=Math.max(x.date+x.duration,y.date+y.duration);await put('walks',{uid:uid(),title:`Combined: ${x.title} + ${y.title}`,activity:x.activity===y.activity?x.activity:'walk',date,duration:end-date,distance:v8RouteDistance(ps),points:ps,tags:['combined'],updatedAt:now()});scheduleCloudSync();await refreshAll();alert('Combined activity created. The originals were kept.') }}

async function v8Voice(){if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return alert('Voice recording is unavailable on this device.');if(v8Recording){v8Recording.stop();return}const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],rec=new MediaRecorder(stream);v8Recording=rec;rec.ondataavailable=e=>chunks.push(e.data);rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:rec.mimeType}),reader=new FileReader();reader.onload=async()=>{await put('voiceNotes',{uid:uid(),activityUid:v8SelectedWalk,date:now(),audio:reader.result,updatedAt:now()});$('v8Voice').textContent='VOICE NOTE';v8Recording=null;v8ShowWalkExtra()};reader.readAsDataURL(blob)};rec.start();$('v8Voice').textContent='STOP RECORDING'}
async function v8BindPhotoTools(){const photos=(await all('photos')).filter(p=>p.activityUid===v8SelectedWalk).sort((a,b)=>a.date-b.date);[...$('walkPhotoGallery').querySelectorAll('img')].forEach((img,i)=>{const p=photos[i];if(!p)return;img.classList.toggle('v8-photo-private',!!p.private);img.title=[p.caption,(p.tags||[]).join(', '),p.annotation].filter(Boolean).join(' · ');img.onclick=async()=>{p.caption=prompt('Photo caption:',p.caption||'')??p.caption;p.tags=(prompt('Photo tags, separated by commas:',(p.tags||[]).join(', '))??'').split(',').map(x=>x.trim()).filter(Boolean);p.annotation=prompt('Photo annotation (what should be circled, pointed out, or remembered):',p.annotation||'')??p.annotation;p.cover=confirm('Use this as the activity cover photo?');p.private=confirm('Keep this photo private from partner sync?');if(p.cover)for(const other of photos)if(other.id!==p.id&&other.cover){other.cover=false;await put('photos',other)}p.updatedAt=now();await put('photos',p);scheduleCloudSync();openWalk(v8SelectedWalk,'mine')}})}

function v8SwitchMap(){const type=$('v8MapStyle').value,provider=V8_MAPS[type]||V8_MAPS.street;map.eachLayer(layer=>{if(layer instanceof L.TileLayer)map.removeLayer(layer)});const layer=v8MapLayer=L.tileLayer(provider.url,{subdomains:provider.subdomains||'abc',maxZoom:provider.maxZoom,attribution:provider.attribution,errorTileUrl:''}).addTo(map);layer.getContainer().style.filter=provider.filter||'';settings.mapStyle=type;saveSettings();let retries=0,retryTimer=null;layer.on('tileerror',()=>{if(navigator.onLine&&retries<2&&!retryTimer){retryTimer=setTimeout(()=>{retryTimer=null;retries++;if(map.hasLayer(layer))layer.redraw()},900*retries+700)}else if(retries>=2)v8Notify(`${provider.label} map missed a tile. Check your connection or use a saved offline area.`)})}
function v8TileXY(lat,lon,z){const n=2**z;return{x:Math.floor((lon+180)/360*n),y:Math.floor((1-Math.asinh(Math.tan(lat*Math.PI/180))/Math.PI)/2*n)}}
function v8TileUrl(provider,z,x,y){const n=2**z;if(y<0||y>=n)return null;x=((x%n)+n)%n;const subs=provider.subdomains||'',s=subs?subs[Math.abs(x+y)%subs.length]:'';return provider.url.replace('{s}',s).replace('{z}',z).replace('{x}',x).replace('{y}',y)}
async function v8SaveOffline(){if(!('caches'in window))return alert('Offline tile storage is unavailable.');const button=$('v8OfflineMap'),c=map.getCenter(),z=Math.min(17,Math.max(10,Math.round(map.getZoom()))),xy=v8TileXY(c.lat,c.lng,z),cache=await caches.open('nights-offline-tiles-v2'),jobs=[];for(const [type,provider] of Object.entries(V8_MAPS))for(let dx=-3;dx<=3;dx++)for(let dy=-3;dy<=3;dy++){const url=v8TileUrl(provider,z,xy.x+dx,xy.y+dy);if(url)jobs.push({type,url})}button.disabled=true;button.textContent=`SAVING 0 / ${jobs.length}`;try{await navigator.storage?.persist?.();const counts={street:0,dark:0,terrain:0,satellite:0};for(let i=0;i<jobs.length;i+=12){await Promise.all(jobs.slice(i,i+12).map(async job=>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const request=new Request(job.url,{mode:'no-cors'}),response=await fetch(request,{cache:'reload',signal:controller.signal});if(response.ok||response.type==='opaque'){await cache.put(request,response.clone());counts[job.type]++}}catch{}finally{clearTimeout(timeout)}}));button.textContent=`SAVING ${Math.min(i+12,jobs.length)} / ${jobs.length}`}const total=Object.values(counts).reduce((a,b)=>a+b,0),details=Object.entries(counts).map(([k,n])=>`${V8_MAPS[k].label}: ${n}`).join(' · ');alert(`Saved ${total} tiles around this area for every map view.\n\n${details}\n\nKeep roughly this zoom level when using the saved area offline.`)}finally{button.disabled=false;button.textContent='SAVE ALL MAPS OFFLINE'}}
async function v8PlanRoute(){const ls=await all('landmarks');if(ls.length<2)return alert('Add at least two landmarks first.');const names=prompt(`Enter landmark names in visit order, separated by commas:\n\n${ls.map(x=>x.name).join(', ')}`);if(!names)return;const chosen=names.split(',').map(n=>ls.find(l=>l.name.toLowerCase()===n.trim().toLowerCase())).filter(Boolean);if(chosen.length<2)return alert('At least two exact landmark names are required.');v8PlanLayer&&map.removeLayer(v8PlanLayer);v8PlanLayer=L.polyline(chosen.map(l=>[l.lat,l.lon]),{color:'#7d3cff',weight:5,dashArray:'8 5'}).addTo(map);map.fitBounds(v8PlanLayer.getBounds(),{padding:[25,25]});await put('plans',{uid:uid(),name:prompt('Plan name:','Landmark route')||'Landmark route',landmarkUids:chosen.map(l=>l.uid),createdAt:now(),updatedAt:now()});alert(`Plan saved: ${chosen.length} stops, approximately ${mi(chosen.slice(1).reduce((s,l,i)=>s+dist(chosen[i],l),0))} miles straight-line.`)}
function v8Breadcrumb(){if(!points?.length||!lastKnownLocation)return alert('Start an activity and wait for GPS first.');v8PlanLayer&&map.removeLayer(v8PlanLayer);v8PlanLayer=L.polyline([[lastKnownLocation.lat,lastKnownLocation.lon],[points[0].lat,points[0].lon]],{color:'#ffd000',weight:6,dashArray:'5 7'}).addTo(map);map.fitBounds(v8PlanLayer.getBounds(),{padding:[25,25]})}
async function v8ToggleHeat(){if(v8HeatLayer){map.removeLayer(v8HeatLayer);v8HeatLayer=null;return}v8HeatLayer=L.layerGroup().addTo(map);for(const w of await all('walks'))for(const p of (w.points||[]).filter((_,i)=>i%15===0))L.circle([p.lat,p.lon],{radius:45,color:'transparent',fillColor:'#ff3600',fillOpacity:.10}).addTo(v8HeatLayer)}

function v8WrapPartner(){const basePoll=pollSharedActivity;pollSharedActivity=async function(){await basePoll();const ps=joinedPartnerActivity?.points||[],p=ps.at(-1);if(p&&map&&settings.partnerPrecise!==false){if(!v8PartnerMarker)v8PartnerMarker=L.circleMarker([p.lat,p.lon],{radius:10,color:'#7d3cff',fillOpacity:.9}).bindTooltip('Partner live position').addTo(map);else v8PartnerMarker.setLatLng([p.lat,p.lon]);$('v8PartnerLive').textContent=`Partner live location: ${new Date(p.t).toLocaleTimeString()} · ±${Math.round(p.accuracy||0)} m`}else $('v8PartnerLive').textContent='Partner live location: waiting'};const baseLeave=leavePartnerActivity;leavePartnerActivity=function(){if(settings.token&&joinedPartnerActivity)authFetch('/api/shared-activity/leave',{method:'POST'}).catch(()=>{});baseLeave()};$('leavePartnerActivity').onclick=leavePartnerActivity}

async function v8CreateBackup(manual=false){const snap=await localSnapshot(),record={createdAt:now(),summary:{walks:snap.walks.length,landmarks:snap.landmarks.length,photos:snap.photos.length},data:snap};await put('backups',record);const backups=(await all('backups')).sort((a,b)=>b.createdAt-a.createdAt);for(const old of backups.slice(3))await remove('backups',old.id);localStorage.setItem('nightsLastAutoBackup',String(record.createdAt));v8BackupHealth(record);if(manual)alert('Local backup completed.')}
async function v8AutoBackup(){const last=Number(localStorage.getItem('nightsLastAutoBackup')||0);if(now()-last>86400000)await v8CreateBackup(false);else{const b=(await all('backups')).sort((a,b)=>b.createdAt-a.createdAt)[0];v8BackupHealth(b)}}
function v8BackupHealth(b){if(!$('v8BackupHealth'))return;$('v8BackupHealth').innerHTML=b?`Last local backup: <b>${formatDate(b.createdAt)}</b><br>${b.summary.walks} activities · ${b.summary.landmarks} landmarks · ${b.summary.photos} photos`:'No automatic backup yet.'}
async function v8LogSync(message){await put('syncHistory',{date:now(),message});const rows=(await all('syncHistory')).sort((a,b)=>b.date-a.date);for(const old of rows.slice(30))await remove('syncHistory',old.id);v8RenderSyncHistory()}
async function v8RenderSyncHistory(){if(!$('v8SyncHistory'))return;const rows=(await all('syncHistory')).sort((a,b)=>b.date-a.date).slice(0,8);$('v8SyncHistory').innerHTML=rows.length?rows.map(x=>`<div><small>${formatDate(x.date)} — ${esc(x.message)}</small></div>`).join(''):'<div class="muted">No sync events recorded yet.</div>'}
function v8UpdateNetwork(){if(!$('v8Network'))return;$('v8Network').innerHTML=navigator.onLine?'<span class="v8-badge v8-good">ONLINE · sync ready</span>':'<span class="v8-badge v8-warn">OFFLINE · changes saved on phone</span>'}
function v8HandleQuickAction(){const q=new URLSearchParams(location.search).get('quick');if(q==='walk'||q==='drive'){showPage('walk');$('activityMode').value=q}else if(q==='landmark'){showPage('landmarks');openNewLandmark()}}
function v8Notify(text){v8Toast(text);try{if(Notification.permission==='granted')new Notification('Nights',{body:text});else if(Notification.permission==='default')Notification.requestPermission()}catch{}}

function v8SaveSettings(){settings.theme=$('v8Theme').value;settings.largeControls=$('v8LargeControls').checked;settings.highContrast=$('v8HighContrast').checked;settings.reduceMotion=$('v8ReduceMotion').checked;settings.routeColor=$('v8RouteColor').value;settings.partnerPrecise=$('v8SharePrecise').checked;settings.partnerRoutes=$('v8ShareRoutes').checked;settings.partnerPhotos=$('v8SharePhotos').checked;settings.partnerLandmarks=$('v8ShareLandmarks').checked;settings.partnerPlans=$('v8SharePlans').checked;saveSettings();v8ApplyTheme();if(account){account.walkColor=settings.routeColor;renderMap();if(settings.token)authFetch('/api/account/walk-color',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({walkColor:settings.routeColor})}).catch(()=>{})}if(settings.token)authFetch('/api/account/sharing',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({routes:settings.partnerRoutes,photos:settings.partnerPhotos,landmarks:settings.partnerLandmarks,plans:settings.partnerPlans})}).catch(()=>{})}
function v8ApplyTheme(){if(!$('v8Theme'))return;$('v8Theme').value=settings.theme||'default';$('v8LargeControls').checked=!!settings.largeControls;$('v8HighContrast').checked=!!settings.highContrast;$('v8ReduceMotion').checked=!!settings.reduceMotion;$('v8SharePrecise').checked=settings.partnerPrecise!==false;$('v8ShareRoutes').checked=settings.partnerRoutes!==false;$('v8SharePhotos').checked=settings.partnerPhotos!==false;$('v8ShareLandmarks').checked=settings.partnerLandmarks!==false;$('v8SharePlans').checked=settings.partnerPlans!==false;document.body.classList.toggle('v8-large',!!settings.largeControls);document.body.classList.toggle('v8-high-contrast',!!settings.highContrast);document.body.classList.toggle('v8-reduce-motion',!!settings.reduceMotion);const colors={default:['#8b0000','#151515'],midnight:['#142d5c','#0b1220'],forest:['#185b37','#0b1b12']}[settings.theme||'default'];document.documentElement.style.setProperty('--accent',colors[0]);document.body.style.backgroundColor=colors[1]}
