/* Nights V9.5: exact MP logs, durable offline partner data, safer ETA graphs,
   street fallback with consent, and immediate current-version startup. */
let v95Ready=false,v95MpLayer=null,v95ScriptLogs=[];

function v95Styles(){const style=document.createElement('style');style.textContent=`
.v95-mp-button{background:#5d218b!important;color:#fff!important;font-weight:900;box-shadow:0 2px 7px #0008}.v95-mp-marker{width:25px;height:25px;border-radius:50%;background:#64238f;color:white;border:3px solid #fff;box-shadow:0 2px 5px #0009;font:bold 10px/20px Arial;text-align:center}.v95-mp-count{min-width:23px;height:23px;border-radius:12px;background:#64238f;color:#fff;border:2px solid #fff;box-shadow:0 2px 5px #0008;font:bold 11px/19px Arial;text-align:center}.v95-mp-card-count{color:#64238f;font-weight:800}.v95-street-key{color:#1976d2;font-weight:800}
body.v95-booting>.topbar,body.v95-booting>.tabs,body.v95-booting>main{visibility:hidden}#v95Boot{position:fixed;inset:0;z-index:999999;background:linear-gradient(#130006,#31000e);color:#fff;display:grid;place-content:center;text-align:center;font:900 28px Tahoma,Arial;letter-spacing:2px}#v95Boot small{font-size:13px;letter-spacing:0;color:#ddd;margin-top:10px}
`;document.head.appendChild(style)}

function v95MpCount(landmark){return v95ScriptLogs.filter(log=>Number.isFinite(+log.lat)&&Number.isFinite(+log.lon)&&dist(log,landmark)<=Number(landmark.radius||50)).length}

async function v95CurrentPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS is unavailable.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:+p.coords.latitude,lon:+p.coords.longitude,accuracy:+p.coords.accuracy||null}),e=>reject(new Error(e.message||'Could not get your location.')),{enableHighAccuracy:true,maximumAge:0,timeout:20000})})}

async function v95LogMp(){const button=$('v95LogMp');button.disabled=true;button.textContent='GETTING GPS…';try{const p=await v95CurrentPosition(),landmarks=await all('landmarks'),hit=landmarks.map(l=>({l,d:dist(p,l)})).filter(x=>x.d<=Number(x.l.radius||50)).sort((a,b)=>a.d-b.d)[0]?.l||null,record={uid:uid(),date:now(),lat:p.lat,lon:p.lon,accuracy:p.accuracy,landmarkUid:hit?.uid||null,updatedAt:now()};await put('scriptLogs',record);v95ScriptLogs=await all('scriptLogs');lastKnownLocation={lat:p.lat,lon:p.lon};scheduleCloudSync();await renderMap();await renderLists();v8Toast(hit?`MP logged at ${hit.name}.`:'MP logged at your exact GPS position.')}catch(e){alert(`MP was not logged: ${e.message}`)}finally{button.disabled=false;button.textContent='LOG MP'}}

async function v95DrawMp(){if(!map)return;v95MpLayer||=L.layerGroup().addTo(map);v95MpLayer.clearLayers();v95ScriptLogs=await all('scriptLogs');for(const log of v95ScriptLogs){if(!Number.isFinite(+log.lat)||!Number.isFinite(+log.lon))continue;L.marker([+log.lat,+log.lon],{icon:L.divIcon({className:'',html:'<div class="v95-mp-marker">MP</div>',iconSize:[25,25],iconAnchor:[12,12]})}).bindPopup(`<b>MP log</b><br>${esc(new Date(log.date).toLocaleString())}<br><small>Saved GPS accuracy: ${log.accuracy?`±${Math.round(log.accuracy)} m`:'unknown'}</small>`).addTo(v95MpLayer)}for(const landmark of await all('landmarks')){const count=v95MpCount(landmark);if(count)L.marker([landmark.lat,landmark.lon],{interactive:false,zIndexOffset:900,icon:L.divIcon({className:'',html:`<div class="v95-mp-count">${count}</div>`,iconSize:[25,25],iconAnchor:[-7,30]})}).addTo(v95MpLayer)}}

async function v95StreetLeg(model,start,end,preference,unavailable){
  if(settings.streetRoutingConsent!==true){const ok=confirm('Use street routing when your recorded network has no route?\n\nIf you allow it, only the route start and destination coordinates are sent through the Nights server to the public OpenStreetMap Valhalla routing service. Your account, walks, landmarks, and MP logs are not sent.');if(!ok)return unavailable;settings.streetRoutingConsent=true;saveSettings()}
  if(!settings.token)return unavailable;
  try{const result=await authFetch('/api/route/street',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:model.mode,start:{lat:+start.lat,lon:+start.lon},end:{lat:+end.lat,lon:+end.lon}})}),pts=result.points||[];if(pts.length<2)return unavailable;const parts=[],totalDistance=pts.slice(1).reduce((n,p,i)=>n+dist(pts[i],p),0),learnedSpeed=Math.max(model.mode==='drive'?2:.38,model.baseSpeed|| (model.mode==='drive'?13.4:1.35)),serverSeconds=Number(result.seconds||0),learnedSeconds=totalDistance/learnedSpeed,totalSeconds=serverSeconds>0?learnedSeconds*.75+serverSeconds*.25:learnedSeconds;for(let i=1;i<pts.length;i++){const d=dist(pts[i-1],pts[i]);parts.push({...v9Section(pts[i-1],pts[i],{distance:d,seconds:totalDistance?totalSeconds*d/totalDistance:0,cost:0,speed:learnedSpeed,grade:0,estimated:true,familiarity:0,timeEvidence:0,sources:0,sourceIds:[],street:true},'Street fallback'),street:true})}const leg=v9FinalizeLeg(start,end,parts,Number(end.radius||0));leg.streetFallback=true;leg.provider=result.source;return leg}catch(e){console.warn('Street route unavailable',e);return unavailable}
}

async function v95RefreshLandmark(saved){if(!saved)return;await v9RecalculateOwnVisits(saved);v9RouteModels={walk:null,drive:null};await v9BuildAllModels();v9ScheduleRoute();await renderLists();await renderMap()}

async function v95Init(){
  if(v95Ready||typeof v94Ready==='undefined'||!v94Ready||typeof v9Started==='undefined'||!v9Started)return false;v95Ready=true;v95Styles();document.querySelector('.brand small').textContent='V9.5.0';
  $('mapbox')?.insertAdjacentHTML('beforebegin','<div class="button-row"><button id="v95LogMp" class="v95-mp-button">LOG MP</button></div>');$('v95LogMp').onclick=v95LogMp;
  const baseMap=renderMap;renderMap=async function(){await baseMap();await v95DrawMp()};
  const baseCard=landmarkCard;landmarkCard=function(l,visits,isPartner=false){const html=baseCard(l,visits,isPartner);if(isPartner)return html;const count=v95MpCount(l);return html.replace('</small>',` · <span class="v95-mp-card-count">${count} MP log${count===1?'':'s'}</span></small>`)};
  const baseLists=renderLists;renderLists=async function(){v95ScriptLogs=await all('scriptLogs');return baseLists()};
  const baseEtaRebuild=rebuildEtaProfile;rebuildEtaProfile=async function(){if(activityEnding){setTimeout(()=>baseEtaRebuild().then(()=>v9BuildAllModels()).catch(e=>console.warn('Background ETA rebuild failed',e)),30);return etaProfile}return baseEtaRebuild()};
  const baseSave=saveLandmark;saveLandmark=async function(e){const oldId=editingLandmarkId,old=oldId?await get('landmarks',oldId):null;await baseSave(e);const saved=oldId?await get('landmarks',oldId):(await all('landmarks')).sort((a,b)=>Number(b.updatedAt||0)-Number(a.updatedAt||0))[0];if(saved&&(!old||Number(old.radius)!==Number(saved.radius)||Number(old.lat)!==Number(saved.lat)||Number(old.lon)!==Number(saved.lon)))await v95RefreshLandmark(saved)};$('lmForm').onsubmit=saveLandmark;
  const baseRoute=v9RenderRoute;v9RenderRoute=function(route){baseRoute(route);if(!route||!v9PlanRouteLayer)return;for(const section of route.sections||[])if(section.street)L.polyline([[section.from.lat,section.from.lon],[section.to.lat,section.to.lon]],{color:'#1976d2',weight:6,opacity:.94}).bindTooltip(`Street fallback · ${mi(section.distance)} mi · learned-speed ETA`).addTo(v9PlanRouteLayer);const key=$('v9RouteKey');if(key&&route.sections?.some(s=>s.street))key.insertAdjacentHTML('beforeend',' <span class="v95-street-key">Blue: streets + your learned pace</span>')};
  await v95DrawMp();await renderLists();document.body.classList.remove('v95-booting');$('v95Boot')?.remove();return true
}

window.addEventListener('nights-ready',()=>{const attempt=()=>v95Init().then(ok=>{if(!ok)setTimeout(attempt,100)});attempt()});
