/* Nights v8.2: voice notes, spatial ETA, route planning, partner landmark editing, and combined memories. */
let v82Started=false,v82VoiceState=null,v82PlanChoices=[],v82PlanStops=[],v82CombineChoices=[],v82CombineSelected=[],v82EditingPartnerUid=null,v82OpeningPartner=false;

window.addEventListener('nights-ready',()=>setTimeout(v82Start,0));
window.addEventListener('load',()=>{let tries=0;const timer=setInterval(()=>{tries++;if((typeof db!=='undefined'&&db&&typeof v8Initialized!=='undefined'&&v8Initialized)||tries>80){clearInterval(timer);if(typeof db!=='undefined'&&db)v82Start()}},250)});

async function v82Start(){
  if(v82Started)return;v82Started=true;
  document.querySelector('.brand small').textContent='V8.2';
  v82Styles();v82BuildUI();v82InstallEta();v82InstallVoice();v82InstallLandmarks();v82InstallMapLandmarkOpening();v82InstallPartnerSync();v82InstallMemories();v82Bind();
  await rebuildEtaProfile();await v82ApplyPendingPartnerEdits();await renderLists();await renderMap();await renderMemories();
}

function v82Styles(){const s=document.createElement('style');s.textContent=`
.v82-picker .dialog{width:min(720px,96vw)}.v82-search-results{max-height:34vh;overflow:auto;margin:8px 0;border:1px solid #888;background:#eee}.v82-result,.v82-stop{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:8px;border-bottom:1px solid #bbb}.v82-result:last-child,.v82-stop:last-child{border-bottom:0}.v82-result button,.v82-stop button{flex:0 0 auto}.v82-owner{font-size:10px;padding:2px 5px;background:#333;color:#fff;margin-left:5px}.v82-selected{border:1px solid #999;background:#fff;margin:8px 0}.v82-plan-summary{padding:8px;background:#202020;color:#fff;font:12px Consolas,monospace}.v82-voice-list{margin-top:8px}.v82-voice{display:grid;grid-template-columns:1fr auto;gap:6px;align-items:center;margin:6px 0}.v82-voice audio{width:100%;min-width:0}.v82-recording{color:#b00020;font-weight:900}.v82-map-open{margin-top:7px;width:100%}`;document.head.appendChild(s)}

function v82BuildUI(){
  const owner=$('memoryOwner');if(owner&&!owner.querySelector('option[value="both"]'))owner.insertAdjacentHTML('beforeend','<option value="both">Mine + partner walks</option>');
  $('v8WalkActions')?.insertAdjacentHTML('afterbegin','<button id="v82RenameWalk">RENAME WALK</button><button id="v82JoinWalk">JOIN WALKS</button>');
  document.body.insertAdjacentHTML('beforeend',`<div id="v82PlanModal" class="modal hidden v82-picker"><div class="dialog"><button class="modal-close" data-v82-close="v82PlanModal">×</button><h2>Plan a landmark trip</h2><p class="muted">Search and add stops in the order you want to visit them. ETA uses your learned pace in these areas and on hills.</p><input id="v82PlanSearch" type="search" placeholder="Search landmark name, category, or notes"><div id="v82PlanResults" class="v82-search-results"></div><h3>Trip stops</h3><div id="v82PlanStops" class="v82-selected"></div><div id="v82PlanSummary" class="v82-plan-summary">Add at least two landmarks.</div><label>Trip name<input id="v82PlanName" value="Landmark trip" maxlength="80"></label><div class="button-row"><button id="v82SavePlan" class="primary">SAVE TRIP</button><button data-v82-close="v82PlanModal">CANCEL</button></div></div></div>`);
  document.body.insertAdjacentHTML('beforeend',`<div id="v82CombineModal" class="modal hidden v82-picker"><div class="dialog"><button class="modal-close" data-v82-close="v82CombineModal">×</button><h2>Join two walks</h2><p class="muted">The originals stay unchanged. Nights creates a new joined memory.</p><input id="v82CombineSearch" type="search" placeholder="Search walk name or date"><div id="v82CombineResults" class="v82-search-results"></div><h3>Selected walks</h3><div id="v82CombineSelected" class="v82-selected"></div><label>Joined walk name<input id="v82CombineName" maxlength="100" placeholder="Joined walk"></label><div class="button-row"><button id="v82SaveCombined" class="primary">CREATE JOINED WALK</button><button data-v82-close="v82CombineModal">CANCEL</button></div></div></div>`);
}

function v82Bind(){
  $('v8Voice').onclick=v82Voice;$('v8Voice').textContent='RECORD VOICE NOTE';$('v8PlanRoute').onclick=v82OpenPlan;$('v82RenameWalk').onclick=v82RenameWalk;$('v82JoinWalk').onclick=()=>v82OpenCombine(v8SelectedWalk);$('v8Compare').onclick=()=>v82OpenCombine();$('v8Compare').textContent='COMPARE / JOIN WALKS';
  $('v82PlanSearch').oninput=v82RenderPlanResults;$('v82SavePlan').onclick=v82SavePlan;$('v82CombineSearch').oninput=v82RenderCombineResults;$('v82SaveCombined').onclick=v82SaveCombined;
  document.querySelectorAll('[data-v82-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.v82Close));
}

function v82GridKey(lat,lon){const size=.00125;return`${Math.round(Number(lat)/size)}:${Math.round(Number(lon)/size)}`}
function v82GradeBucket(percent){return percent>=9?'steep-up':percent>=3.5?'uphill':percent<=-9?'steep-down':percent<=-3.5?'downhill':'level'}
function v82InstallEta(){rebuildEtaProfile=v82RebuildEtaProfile;walkEstimateData=v82WalkEstimateData;window.nightsEstimatePath=v82EstimatePath}
async function v82RebuildEtaProfile(){
  const sourceWalks=typeof v92EtaWalkSources==='function'?await v92EtaWalkSources('walk'):await all('walks'),walks=sourceWalks.filter(w=>(w.activity||'walk')==='walk'&&!w.combinedFrom?.length&&Number(w.distance)>100&&Number(w.duration)>60000),timeStats={},distanceStats={},spatial={},grades={},route=[];let totalD=0,totalT=0,validWalks=0,segments=0;
  const add=(group,key,d,t,grade=null)=>{const x=group[key]||{distance:0,time:0,samples:0,gradeTotal:0,gradeSamples:0};x.distance+=d;x.time+=t;x.samples++;if(Number.isFinite(grade)){x.gradeTotal+=grade;x.gradeSamples++}group[key]=x};
  for(const w of walks){
    const cleaned=nightsQualitySegments(w.points,'walk'), ps=cleaned.segments;
    const d=ps.reduce((n,s)=>n+s.distance,0),sec=ps.reduce((n,s)=>n+s.seconds,0);
    if(d<50||sec<=0)continue;
    validWalks++;totalD+=d;totalT+=sec;
    add(timeStats,timeBucket(w.date),d,sec);add(distanceStats,distanceBucket(d),d,sec);
    if(!cleaned.stats.gaps&&!cleaned.stats.jumps&&!cleaned.stats.poorAccuracy&&ps.length){
      const direct=dist(ps[0].a,ps.at(-1).b);if(direct>150)route.push(Math.min(1.85,Math.max(1.03,d/direct)));
    }
    for(const {a,b,distance,seconds,grade} of ps){
      const mid={lat:(a.lat+b.lat)/2,lon:(a.lon+b.lon)/2};add(spatial,v82GridKey(mid.lat,mid.lon),distance,seconds,grade);
      if(Number.isFinite(grade))add(grades,v82GradeBucket(grade),distance,seconds,grade);segments++;
    }
  }
  const convert=x=>Object.fromEntries(Object.entries(x).map(([k,v])=>[k,{speed:Math.min(3,Math.max(.35,v.distance/Math.max(1,v.time))),samples:v.samples,grade:v.gradeSamples?v.gradeTotal/v.gradeSamples:null}]));
  etaProfile={baseSpeed:totalT?Math.min(2.4,Math.max(.55,totalD/totalT)):1.4,routeFactor:route.length?route.reduce((a,b)=>a+b,0)/route.length:1.2,timeSpeeds:Object.fromEntries(Object.entries(convert(timeStats)).map(([k,v])=>[k,v.speed])),distanceSpeeds:Object.fromEntries(Object.entries(convert(distanceStats)).map(([k,v])=>[k,v.speed])),spatialSpeeds:convert(spatial),gradeSpeeds:convert(grades),sampleCount:validWalks,segmentSamples:segments,learnedAreas:Object.keys(spatial).length,hilliness:0};
  etaProfile.source=settings.etaSource||'mine';etaProfile.sourceLabel=typeof v92EtaSourceLabel==='function'?v92EtaSourceLabel():"My walks";
  if($('etaLearning'))$('etaLearning').textContent=validWalks?`ETA model: ${etaProfile.sourceLabel} · ${validWalks} usable walks · ${etaProfile.learnedAreas} learned areas · ${segments} pace segments`:`ETA model: no usable ${etaProfile.sourceLabel.toLowerCase()} yet`;
}
function v82BasePace(distance,date=Date.now()){let total=(etaProfile.baseSpeed||1.4)*2,weight=2;const ts=etaProfile.timeSpeeds?.[timeBucket(date)],ds=etaProfile.distanceSpeeds?.[distanceBucket(distance)];if(ts){total+=ts;weight++}if(ds){total+=ds;weight++}return Math.min(3,Math.max(.4,total/weight))}
function v82NearbyPace(lat,lon){const size=.00125,cx=Math.round(Number(lat)/size),cy=Math.round(Number(lon)/size),hits=[];for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++){const s=etaProfile.spatialSpeeds?.[`${cx+x}:${cy+y}`];if(s?.samples)hits.push(s)}if(!hits.length)return null;const weight=hits.reduce((n,s)=>n+Math.min(12,s.samples),0);return{speed:hits.reduce((n,s)=>n+s.speed*Math.min(12,s.samples),0)/weight,samples:hits.reduce((n,s)=>n+s.samples,0)}}
function v82EstimateSegment(a,b,totalDistance,useCurrentGrade=false){const d=dist(a,b),steps=Math.max(1,Math.ceil(d/75)),base=v82BasePace(totalDistance);let seconds=0,matched=0;for(let i=0;i<steps;i++){const f=(i+.5)/steps,lat=Number(a.lat)+(Number(b.lat)-Number(a.lat))*f,lon=Number(a.lon)+(Number(b.lon)-Number(a.lon))*f,local=v82NearbyPace(lat,lon);let speed=local?base*.3+local.speed*.7:base;if(local)matched++;if(useCurrentGrade&&i===0&&Number.isFinite(Number(currentSlopePercent))){const gs=etaProfile.gradeSpeeds?.[v82GradeBucket(Number(currentSlopePercent))];if(gs)speed=speed*.55+gs.speed*.45;else speed/=1+Math.min(.18,Math.abs(Number(currentSlopePercent))/100*.7)}seconds+=(d/steps)/Math.max(.4,speed)}return{distance:d,seconds,matched,samples:steps}}
function v82EstimatePath(path,applyRoadFactor=true){let direct=0,seconds=0,matched=0,samples=0;for(let i=1;i<path.length;i++){const x=v82EstimateSegment(path[i-1],path[i],direct||dist(path[i-1],path[i]),i===1);direct+=x.distance;seconds+=x.seconds;matched+=x.matched;samples+=x.samples}const factor=applyRoadFactor?(etaProfile.routeFactor||1.2):1;return{meters:direct*factor,seconds:seconds*factor,mins:Math.max(1,Math.round(seconds*factor/60)),matched,samples}}
function v82WalkEstimateData(l){if(!lastKnownLocation)return null;const e=v82EstimatePath([lastKnownLocation,l],true),confidence=etaProfile.sampleCount>=8?'high':etaProfile.sampleCount>=3?'learning':'starter',local=e.matched?` · ${e.matched} learned area${e.matched===1?'':'s'}`:'',source=etaProfile.sourceLabel||'My walks';return{meters:e.meters,miles:e.meters/1609.344,mins:e.mins,text:`~${e.mins} min · ${mi(e.meters)} mi · ${confidence} ETA${local} · ${source}`,details:`${source}: speed by location, distance, direction, and learned uphill/downhill pace`}}

function v82InstallVoice(){v8Voice=v82Voice;v8ShowWalkExtra=v82ShowWalkExtra}
async function v82ShowWalkExtra(){const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk);if(!w)return;const notes=(await all('voiceNotes')).filter(n=>n.activityUid===w.uid).sort((a,b)=>b.date-a.date),voice=notes.length?`<div class="v82-voice-list">${notes.map(n=>/^data:audio\//i.test(n.audio||'')?`<div class="v82-voice"><div><audio controls preload="metadata" src="${n.audio}"></audio><small>${esc(formatDate(n.date))}${n.duration?` · ${Math.round(n.duration/1000)} sec`:''}</small></div><button data-v82-delete-voice="${n.id}" class="danger">DELETE</button></div>`:'').join('')}</div>`:'<span class="muted">No voice notes yet.</span>';$('v8WalkExtra').innerHTML=`${w.notes?`<b>Notes:</b> ${esc(w.notes)}<br>`:''}${w.tags?.length?`<b>Tags:</b> ${w.tags.map(esc).join(', ')}<br>`:''}${w.rating?`<b>Rating:</b> ${'★'.repeat(w.rating)}<br>`:''}${w.comments?.length?`<b>Comments:</b> ${w.comments.map(x=>esc(x.text||x)).join(' · ')}<br>`:''}<b>Voice notes:</b>${voice}`;document.querySelectorAll('[data-v82-delete-voice]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this voice note?')){await remove('voiceNotes',Number(b.dataset.v82DeleteVoice));v82ShowWalkExtra()}})}
async function v82Voice(){
  if(v82VoiceState){v82VoiceState.recorder.stop();return}
  if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return alert('Voice recording is unavailable on this device.');
  try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}),chunks=[],started=now(),types=['audio/webm;codecs=opus','audio/webm','audio/mp4'],mime=types.find(t=>MediaRecorder.isTypeSupported?.(t))||'',rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);v82VoiceState={recorder:rec,stream,started};rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};rec.onerror=e=>{stream.getTracks().forEach(t=>t.stop());v82VoiceState=null;$('v8Voice').textContent='RECORD VOICE NOTE';alert(`Voice recording failed: ${e.error?.message||'microphone error'}`)};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());v82VoiceState=null;$('v8Voice').textContent='RECORD VOICE NOTE';if(!chunks.length)return alert('No audio was captured. Check the microphone permission and try again.');const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'}),audio=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)});await put('voiceNotes',{uid:uid(),activityUid:v8SelectedWalk,date:started,duration:now()-started,mimeType:blob.type,audio,updatedAt:now()});await v82ShowWalkExtra();v8Toast('Voice note saved.')};rec.start(250);$('v8Voice').textContent='STOP & SAVE VOICE';$('v8WalkExtra').insertAdjacentHTML('afterbegin','<div class="v82-recording">● Recording voice note…</div>')}catch(e){v82VoiceState=null;$('v8Voice').textContent='RECORD VOICE NOTE';alert(e.name==='NotAllowedError'?'Microphone access is off. Allow the Microphone permission for Nights, then try again.':`Could not start voice recording: ${e.message}`)}}

function v82InstallLandmarks(){
  const baseOpen=openLandmarkEditor;openLandmarkEditor=function(l,id){if(!v82OpeningPartner)v82EditingPartnerUid=null;baseOpen(l,id);const partnerEdit=!!v82EditingPartnerUid;$('lmTitle').textContent=partnerEdit?`Edit ${partner?.displayName||'partner'} landmark`:(id?'Edit landmark':'Add landmark');$('v8FavoriteLandmark')?.classList.toggle('hidden',partnerEdit);$('v8LandmarkHistory')?.classList.toggle('hidden',partnerEdit)};
  const baseSave=saveLandmark;saveLandmark=async function(e){if(!v82EditingPartnerUid)return baseSave(e);e.preventDefault();const radiusFeet=Number($('lmRadius').value);if(!Number.isFinite(radiusFeet)||radiusFeet<1)return alert('Enter a detection radius of at least 1 foot.');const existing=(partnerSnapshot?.landmarks||[]).find(x=>x.uid===v82EditingPartnerUid);if(!existing)return alert('That partner landmark is no longer available.');const zones=($('v8LmZones')?.value||'').split(',').map(Number).filter(x=>Number.isFinite(x)&&x>0),record={...existing,name:$('lmName').value.trim(),category:$('lmCategory').value.trim()||'Other',subcategory:$('lmSubcategory').value.trim(),rating:Number($('lmRating').value),desc:$('lmDesc').value.trim(),notes:$('lmNotes').value.trim(),radius:feetToMeters(radiusFeet),lat:Number($('lmLat').value),lon:Number($('lmLon').value),photos:[...editingPhotos],photo:editingPhotos[0]||'',zonesFeet:zones,updatedAt:now()};delete record.id;const i=partnerSnapshot.landmarks.findIndex(x=>x.uid===record.uid);partnerSnapshot.landmarks[i]=record;v82QueuePartnerEdit(record);closeModal('landmarkModal');v82EditingPartnerUid=null;await renderLists();await renderMap();const synced=await v82SyncPartnerEdits(true);alert(synced?'Partner landmark updated.':'The edit is saved on this phone and queued until partner sync is available.')};$('lmForm').onsubmit=saveLandmark;
  const baseCard=landmarkCard;landmarkCard=function(l,visits,isPartner=false){const html=baseCard(l,visits,isPartner);return isPartner?html.replace('class="window-card landmark "',`class="window-card landmark clickable" data-v82-partner-landmark="${esc(l.uid)}"`):html};
  const baseRender=renderLists;renderLists=async function(){await baseRender();document.querySelectorAll('[data-v82-partner-landmark]').forEach(el=>el.onclick=()=>v82OpenLandmark(el.dataset.v82PartnerLandmark,'partner'));v82UpdateMemoryLabels()};
}
async function v82OpenLandmark(uidValue,owner='mine'){showPage('landmarks');await renderLists();if(owner==='partner'){const l=(partnerSnapshot?.landmarks||[]).find(x=>x.uid===uidValue);if(!l)return alert('Partner landmark unavailable.');v82EditingPartnerUid=l.uid;v82OpeningPartner=true;openLandmarkEditor(l,null);v82OpeningPartner=false}else{const l=(await all('landmarks')).find(x=>x.uid===uidValue);if(l)openLandmarkEditor(l,l.id)}}
function v82PendingPartnerEdits(){return Array.isArray(settings.pendingPartnerLandmarkEdits)?settings.pendingPartnerLandmarkEdits:[]}
function v82QueuePartnerEdit(record){const q=v82PendingPartnerEdits(),i=q.findIndex(x=>x.uid===record.uid);if(i>=0)q[i]=record;else q.push(record);settings.pendingPartnerLandmarkEdits=q;saveSettings()}
async function v82SyncPartnerEdits(silent=false){const pending=v82PendingPartnerEdits();if(settings.pendingPartnerLandmarkEdits!==pending){settings.pendingPartnerLandmarkEdits=pending;saveSettings()}if(!settings.token||!partner||!pending.length)return 0;let count=0;for(const edit of [...pending])try{const r=await authFetch('/api/partner-landmark',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({landmark:edit})});if(r.landmark){const i=partnerSnapshot?.landmarks?.findIndex(x=>x.uid===r.landmark.uid);if(i>=0)partnerSnapshot.landmarks[i]=r.landmark;if(Array.isArray(r.visits)&&partnerSnapshot)partnerSnapshot.visits=[...(partnerSnapshot.visits||[]).filter(x=>x.landmarkUid!==r.landmark.uid),...r.visits]}settings.pendingPartnerLandmarkEdits=v82PendingPartnerEdits().filter(x=>x.uid!==edit.uid);saveSettings();count++}catch(e){if(!silent&&e.status!==404)console.warn('Partner landmark sync:',e.message)}return count}
async function v82ApplyPendingPartnerEdits(){if(!partnerSnapshot)return;for(const edit of v82PendingPartnerEdits()){const i=partnerSnapshot.landmarks.findIndex(x=>x.uid===edit.uid);if(i>=0&&Number(edit.updatedAt)>=Number(partnerSnapshot.landmarks[i].updatedAt||0))partnerSnapshot.landmarks[i]=edit}await v82SyncPartnerEdits(true)}
function v82InstallPartnerSync(){const base=loadPartnerOnly;loadPartnerOnly=async function(){await base();await v82ApplyPendingPartnerEdits();v82UpdateMemoryLabels();await renderMap();await renderLists()}}

function v82RouteSegments(ps){const result=[];let segment=[];for(const p of ps||[]){if(p.segmentBreak&&segment.length){result.push(nightsDisplayPoints(segment,3000));segment=[]}segment.push(p)}if(segment.length)result.push(nightsDisplayPoints(segment,3000));return result}
async function v82RenderSplitRoutes(){if(!map)return;const mode=$('mapOwner')?.value||'mine',myColor=safeColor(account?.walkColor,'#d00000'),partnerColor=safeColor(partner?.walkColor,'#777777');routeLayer?.clearLayers();partnerRouteLayer?.clearLayers();if(mode!=='partner')for(const w of await all('walks'))for(const ps of v82RouteSegments(w.points))if(ps.length>1)L.polyline(ps.map(p=>[p.lat,p.lon]),{weight:4,opacity:.86,color:myColor}).bindTooltip(esc(w.title||'Activity')).addTo(routeLayer);if(mode!=='mine'&&partnerSnapshot)for(const w of partnerSnapshot.walks||[])for(const ps of v82RouteSegments(w.points))if(ps.length>1)L.polyline(ps.map(p=>[p.lat,p.lon]),{weight:4,opacity:.78,color:partnerColor,dashArray:'7 5'}).bindTooltip(`${esc(partner?.displayName||'Partner')}: ${esc(w.title||'Activity')}`).addTo(partnerRouteLayer)}
function v82InstallMapLandmarkOpening(){const base=renderMap;renderMap=async function(){await base();await v82RenderSplitRoutes();v82WireLandmarkLayer(landmarkLayer,'mine');v82WireLandmarkLayer(partnerLandmarkLayer,'partner')};const baseOpen=openWalk;openWalk=async function(uidValue,owner='mine'){await baseOpen(uidValue,owner);const d=owner==='partner'?partnerSnapshot:await localSnapshot(),w=(d?.walks||[]).find(x=>x.uid===uidValue);if(!(w?.points||[]).some(p=>p.segmentBreak))return;setTimeout(()=>{if(!walkModalLayer)return;walkModalLayer.eachLayer(layer=>{if(layer instanceof L.Polyline)walkModalLayer.removeLayer(layer)});const color=owner==='partner'?safeColor(partner?.walkColor,'#777777'):safeColor(account?.walkColor,'#d00000');for(const ps of v82RouteSegments(w.points))if(ps.length>1)L.polyline(ps.map(p=>[p.lat,p.lon]),{weight:5,color}).addTo(walkModalLayer)},120)}}
function v82WireLandmarkLayer(group,owner){group?.eachLayer(marker=>{if(marker.__v82Open)return;marker.__v82Open=true;marker.on('popupopen',()=>{const source=owner==='partner'?(partnerSnapshot?.landmarks||[]):null,ll=marker.getLatLng();Promise.resolve(source||all('landmarks')).then(ls=>{const l=ls.find(x=>Math.abs(Number(x.lat)-ll.lat)<1e-7&&Math.abs(Number(x.lon)-ll.lng)<1e-7);if(!l)return;const popup=marker.getPopup()?.getElement();if(!popup||popup.querySelector('.v82-map-open'))return;const b=document.createElement('button');b.className='v82-map-open';b.textContent=`OPEN ${owner==='partner'?(partner?.displayName||'PARTNER').toUpperCase()+' ':''}LANDMARK`;b.onclick=()=>{map.closePopup();v82OpenLandmark(l.uid,owner)};popup.querySelector('.leaflet-popup-content')?.appendChild(b)})})})}

async function v82OpenPlan(){const mine=await all('landmarks'),theirs=partnerSnapshot?.landmarks||[];v82PlanChoices=[...mine.map(l=>({...l,_owner:'mine'})),...theirs.map(l=>({...l,_owner:'partner'}))];v82PlanStops=[];$('v82PlanSearch').value='';$('v82PlanName').value='Landmark trip';v82RenderPlanResults();v82RenderPlanStops();$('v82PlanModal').classList.remove('hidden');$('v82PlanSearch').focus()}
function v82RenderPlanResults(){const q=$('v82PlanSearch').value.trim().toLowerCase(),found=v82PlanChoices.filter(l=>!q||[l.name,l.category,l.subcategory,l.desc,l.notes].join(' ').toLowerCase().includes(q)).slice(0,40);$('v82PlanResults').innerHTML=found.length?found.map((l,i)=>`<div class="v82-result"><span><b>${esc(l.name)}</b><span class="v82-owner">${l._owner==='partner'?esc(partner?.displayName||'PARTNER'):'MINE'}</span><br><small>${esc([l.category,l.subcategory].filter(Boolean).join(' › '))}</small></span><button data-v82-plan-add="${i}">ADD</button></div>`).join(''):'<div class="empty">No landmarks match.</div>';document.querySelectorAll('[data-v82-plan-add]').forEach(b=>b.onclick=()=>{const l=found[Number(b.dataset.v82PlanAdd)],key=`${l._owner}:${l.uid}`;if(!v82PlanStops.some(x=>`${x._owner}:${x.uid}`===key))v82PlanStops.push(l);v82RenderPlanStops()})}
function v82RenderPlanStops(){const path=[...(lastKnownLocation?[lastKnownLocation]:[]),...v82PlanStops],estimate=path.length>1?v82EstimatePath(path,true):null;$('v82PlanStops').innerHTML=v82PlanStops.length?v82PlanStops.map((l,i)=>`<div class="v82-stop"><span><b>${i+1}. ${esc(l.name)}</b><span class="v82-owner">${l._owner==='partner'?esc(partner?.displayName||'PARTNER'):'MINE'}</span></span><span><button data-v82-up="${i}">▲</button><button data-v82-down="${i}">▼</button><button data-v82-remove="${i}">✕</button></span></div>`).join(''):'<div class="empty">Search above and add stops.</div>';$('v82PlanSummary').textContent=estimate?`${mi(estimate.meters)} mi · about ${estimate.mins} min · ${estimate.matched} learned area samples used`:'Add at least two landmarks.';document.querySelectorAll('[data-v82-up]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.v82Up);if(i){[v82PlanStops[i-1],v82PlanStops[i]]=[v82PlanStops[i],v82PlanStops[i-1]];v82RenderPlanStops()}});document.querySelectorAll('[data-v82-down]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.v82Down);if(i<v82PlanStops.length-1){[v82PlanStops[i+1],v82PlanStops[i]]=[v82PlanStops[i],v82PlanStops[i+1]];v82RenderPlanStops()}});document.querySelectorAll('[data-v82-remove]').forEach(b=>b.onclick=()=>{v82PlanStops.splice(Number(b.dataset.v82Remove),1);v82RenderPlanStops()})}
async function v82SavePlan(){if(v82PlanStops.length<2)return alert('Add at least two landmarks.');const route=[...(lastKnownLocation?[lastKnownLocation]:[]),...v82PlanStops],estimate=v82EstimatePath(route,true),legs=[];for(let i=1;i<route.length;i++){const e=v82EstimatePath([route[i-1],route[i]],true),from=i===1&&lastKnownLocation?'Your location':v82PlanStops[i-(lastKnownLocation?2:1)]?.name||'Start',to=v82PlanStops[i-(lastKnownLocation?1:0)]?.name||'Stop';legs.push(`${from} → ${to}: ~${e.mins} min`)}v8PlanLayer&&map.removeLayer(v8PlanLayer);v8PlanLayer=L.polyline(route.map(x=>[x.lat,x.lon]),{color:'#7d3cff',weight:5,dashArray:'8 5'}).addTo(map);map.fitBounds(v8PlanLayer.getBounds(),{padding:[25,25]});const name=$('v82PlanName').value.trim()||'Landmark trip';await put('plans',{uid:uid(),name,landmarkUids:v82PlanStops.map(x=>x.uid),stops:v82PlanStops.map(x=>({uid:x.uid,owner:x._owner,name:x.name,lat:x.lat,lon:x.lon})),distance:estimate.meters,estimatedDuration:estimate.seconds,etaModel:'personal-spatial-v2',createdAt:now(),updatedAt:now()});scheduleCloudSync();closeModal('v82PlanModal');alert(`${name}\n\n${legs.join('\n')}\n\nTotal: ${mi(estimate.meters)} mi · about ${estimate.mins} min. ETA used your learned pace in ${estimate.matched} nearby area samples.`)}

function v82InstallMemories(){renderMemories=v82RenderMemories;$('memoryOwner').onchange=renderMemories;v82UpdateMemoryLabels()}
function v82UpdateMemoryLabels(){const p=partner?.displayName||'Partner',owner=$('memoryOwner');if(!owner)return;const po=owner.querySelector('option[value="partner"]'),bo=owner.querySelector('option[value="both"]');if(po)po.textContent=`${p} walks`;if(bo)bo.textContent=`Mine + ${p} walks`}
async function v82MemoryData(owner){const mine=await localSnapshot();if(owner==='partner')return partnerSnapshot?{...partnerSnapshot,walks:(partnerSnapshot.walks||[]).map(w=>({...w,_owner:'partner'}))}:null;if(owner==='both'){const theirs=partnerSnapshot||{walks:[],landmarks:[],visits:[],photos:[]};return{walks:[...(mine.walks||[]).map(w=>({...w,_owner:'mine'})),...(theirs.walks||[]).map(w=>({...w,_owner:'partner'}))],landmarks:[...(mine.landmarks||[]),...(theirs.landmarks||[])],visits:[...(mine.visits||[]),...(theirs.visits||[])],photos:[...(mine.photos||[]),...(theirs.photos||[])]}}return{...mine,walks:(mine.walks||[]).map(w=>({...w,_owner:'mine'}))}}
async function v82RenderMemories(){const owner=$('memoryOwner').value,d=await v82MemoryData(owner);if(!d){$('statsGrid').innerHTML='<div class="window-card">No partner data loaded.</div>';$('walkList').innerHTML='';$('v8Insights').innerHTML='';return}const month=$('v8MemoryDate')?.value,allWalks=d.walks||[],ws=month?allWalks.filter(w=>new Date(w.date).toISOString().slice(0,7)===month):allWalks,walks=ws.filter(w=>(w.activity||'walk')==='walk'),drives=ws.filter(w=>w.activity==='drive'),total=walks.reduce((s,w)=>s+Number(w.distance||0),0),pname=partner?.displayName||'Partner';$('statsGrid').innerHTML=`<div class="window-card"><div class="stat">${walks.length}</div><small>walks</small></div><div class="window-card"><div class="stat">${drives.length}</div><small>drives</small></div><div class="window-card"><div class="stat">${mi(total)}</div><small>walk miles</small></div><div class="window-card"><div class="stat">${(d.landmarks||[]).length}</div><small>landmarks</small></div>`;$('walkHistoryTitle').textContent=owner==='both'?`Mine + ${pname} activities`:owner==='partner'?`${pname} activities`:'Recent activities';$('walkList').innerHTML=ws.length?[...ws].sort((a,b)=>b.date-a.date).map(w=>`<div class="window-card clickable walk-row" data-walk-uid="${esc(w.uid)}" data-walk-owner="${w._owner||owner}"><div><b>${esc(w.title||activityLabel(w))}</b><span class="activity-type ${w.activity==='drive'?'drive-type':''}">${activityLabel(w).toUpperCase()}</span>${owner==='both'?`<span class="partner-tag">${w._owner==='partner'?esc(pname):'MINE'}</span>`:''}<div>${mi(w.distance)} mi · ${ft(w.duration)}</div></div><div class="muted">${esc(formatDate(w.date))}<br>${(w.points||[]).length} GPS points</div></div>`).join(''):'<div class="empty">No saved activities match.</div>';document.querySelectorAll('[data-walk-uid]').forEach(el=>el.onclick=()=>openWalk(el.dataset.walkUid,el.dataset.walkOwner));v82RenderInsights(d,ws,month)}
function v82RenderInsights(d,walks,month){const longest=[...walks].sort((a,b)=>Number(b.distance)-Number(a.distance))[0],elev=[...walks].sort((a,b)=>elevationStats(b).gain-elevationStats(a).gain)[0],areas=new Set(walks.flatMap(w=>(w.points||[]).map(p=>`${Number(p.lat).toFixed(2)},${Number(p.lon).toFixed(2)}`))).size,months={};for(const w of walks){const k=new Date(w.date).toISOString().slice(0,7);months[k]=(months[k]||0)+Number(w.distance||0)}const trend=Object.entries(months).sort().slice(-6),max=Math.max(1,...trend.map(x=>x[1]));$('v8Insights').innerHTML=`<div class="window-card"><b>${walks.length}</b>activities${month?' this month':''}</div><div class="window-card"><b>${longest?mi(longest.distance):'0.00'} mi</b>longest</div><div class="window-card"><b>${elev?Math.round(elevationStats(elev).gain*3.28084):0} ft</b>most climbing</div><div class="window-card"><b>${areas}</b>map areas explored</div><div class="window-card" style="grid-column:1/-1"><b>Distance trend</b><div style="display:flex;align-items:end;height:100px;gap:6px">${trend.map(([k,v])=>`<span title="${k}: ${mi(v)} mi" style="flex:1;background:#b12222;height:${Math.max(5,v/max*80)}px"><small>${k.slice(5)}</small></span>`).join('')}</div></div>`}

async function v82RenameWalk(){const w=(await all('walks')).find(x=>x.uid===v8SelectedWalk);if(!w)return;const title=prompt('New walk name:',w.title||activityLabel(w));if(!title?.trim())return;w.title=title.trim();w.updatedAt=now();await put('walks',w);scheduleCloudSync();await refreshAll();await openWalk(w.uid,'mine');v8Toast('Walk renamed.')}
async function v82OpenCombine(firstUid=null){v82CombineChoices=(await all('walks')).filter(w=>(w.activity||'walk')==='walk').sort((a,b)=>b.date-a.date);if(v82CombineChoices.length<2)return alert('You need at least two walks to join.');v82CombineSelected=firstUid?v82CombineChoices.filter(x=>x.uid===firstUid):[];$('v82CombineSearch').value='';$('v82CombineName').value='';v82RenderCombineResults();v82RenderCombineSelected();$('v82CombineModal').classList.remove('hidden');$('v82CombineSearch').focus()}
function v82RenderCombineResults(){const q=$('v82CombineSearch').value.trim().toLowerCase(),found=v82CombineChoices.filter(w=>!v82CombineSelected.some(x=>x.uid===w.uid)&&(!q||`${w.title} ${formatDate(w.date)}`.toLowerCase().includes(q))).slice(0,40);$('v82CombineResults').innerHTML=found.length?found.map((w,i)=>`<div class="v82-result"><span><b>${esc(w.title||'Walk')}</b><br><small>${esc(formatDate(w.date))} · ${mi(w.distance)} mi</small></span><button data-v82-combine-add="${i}">ADD</button></div>`).join(''):'<div class="empty">No matching walks.</div>';document.querySelectorAll('[data-v82-combine-add]').forEach(b=>b.onclick=()=>{if(v82CombineSelected.length>=2)return alert('Remove a selected walk first.');v82CombineSelected.push(found[Number(b.dataset.v82CombineAdd)]);v82RenderCombineSelected();v82RenderCombineResults()})}
function v82RenderCombineSelected(){$('v82CombineSelected').innerHTML=v82CombineSelected.length?v82CombineSelected.map((w,i)=>`<div class="v82-stop"><span><b>${i+1}. ${esc(w.title||'Walk')}</b><br><small>${mi(w.distance)} mi · ${ft(w.duration)}</small></span><button data-v82-combine-remove="${i}">REMOVE</button></div>`).join(''):'<div class="empty">Select two walks.</div>';if(v82CombineSelected.length===2&&!$('v82CombineName').value)$('v82CombineName').value=`${v82CombineSelected[0].title||'Walk'} + ${v82CombineSelected[1].title||'Walk'}`;document.querySelectorAll('[data-v82-combine-remove]').forEach(b=>b.onclick=()=>{v82CombineSelected.splice(Number(b.dataset.v82CombineRemove),1);v82RenderCombineSelected();v82RenderCombineResults()})}
async function v82SaveCombined(){if(v82CombineSelected.length!==2)return alert('Select exactly two walks.');const chosen=[...v82CombineSelected].sort((a,b)=>a.date-b.date),newUid=uid(),points=[];for(let wi=0;wi<chosen.length;wi++){const source=chosen[wi].points||[],offset=points.length&&source.length&&Number(source[0].t)<=Number(points.at(-1).t)?Number(points.at(-1).t)-Number(source[0].t)+1000:0;source.forEach((p,i)=>points.push({...p,t:Number(p.t||0)+offset,...(wi&&i===0?{segmentBreak:true}:{})}))}const title=$('v82CombineName').value.trim()||`Joined: ${chosen[0].title} + ${chosen[1].title}`,combinedFrom=[...new Set(chosen.flatMap(w=>[w.uid,...(w.combinedFrom||[])]))],record={uid:newUid,title,activity:'walk',date:Math.min(...chosen.map(w=>Number(w.date))),duration:chosen.reduce((s,w)=>s+Number(w.duration||0),0),distance:chosen.reduce((s,w)=>s+Number(w.distance||0),0),points,combinedFrom,tags:['joined'],elevationGain:chosen.reduce((s,w)=>s+elevationStats(w).gain,0),elevationLoss:chosen.reduce((s,w)=>s+elevationStats(w).loss,0),updatedAt:now()};await put('walks',record);closeModal('v82CombineModal');scheduleCloudSync();await refreshAll();alert('Joined walk created. Both original walks were kept.');await openWalk(newUid,'mine')}
